import {buildFeedbackIssue} from './feedback-issue.js';
import {suggestUsage} from './asset-usage.js';
import {cameraPresets,pixelStyles,styleColor} from './appearance.js';
import {examples,createExample} from './examples.js';
import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {zipSync,strToU8} from 'fflate';
const $=s=>document.querySelector(s), TAU=Math.PI*2;
const names=['Vorne','Vorne rechts','Rechts','Hinten rechts','Hinten','Hinten links','Links','Vorne links'];
const motions=['still','float','hop'],frames=12,fps=12;
let model,modelBytes,testBytes,sourceName='MOMO',direction=0,motion='float',paused=false,ready=false,baking=false,elapsed=0,last=0,resolution=64,sheet,atlas=[],generation=0,sourceAngle=0;
const appearance={camera:'iso',size:100,front:0,style:'studio'};
let activeExample=examples[0],modelInfo={},licenseDocs={},bakeMilliseconds=0;
const status=message=>$('#status').textContent=message;
const renderer=new THREE.WebGLRenderer({alpha:true,antialias:false,preserveDrawingBuffer:true});renderer.setPixelRatio(1);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setClearColor(0,0);
const scene=new THREE.Scene(),pivot=new THREE.Group();scene.add(pivot);
scene.add(new THREE.HemisphereLight(0xf6ffe6,0x68737c,2.3));const light=new THREE.DirectionalLight(0xfff2dc,3);light.position.set(-3,6,5);scene.add(light);
const rim=new THREE.DirectionalLight(0xc0eacb,1.4);rim.position.set(4,3,-4);scene.add(rim);
const camera=new THREE.OrthographicCamera(-1.65,1.65,1.65,-1.65,.1,50);camera.position.set(0,3.2,7);camera.lookAt(0,1,0);camera.updateMatrixWorld();
const origin=new THREE.Vector3(0,0,0).project(camera);const anchor={x:.5,y:(1-origin.y)/2};
const sourceCanvas=$('#source'),sourceCtx=sourceCanvas.getContext('2d'),pixelCtx=$('#pixel').getContext('2d'),world=$('#world'),ctx=world.getContext('2d');
function mat(color,roughness=.55,metalness=0){return new THREE.MeshStandardMaterial({color,roughness,metalness})}
function testModel(){const g=new THREE.Group();g.name='MOMO_static_collectible';const cream=mat('#eee2b9'),green=mat('#7f9f73'),dark=mat('#233c37'),orange=mat('#ee8552'),glass=mat('#203c3e',.24,.2),gold=mat('#e9b965',.4,.15);
 function part(geometry,material,pos,scale){const mesh=new THREE.Mesh(geometry,material);mesh.position.set(...pos);if(scale)mesh.scale.set(...scale);g.add(mesh);return mesh}
 const sphere=(m,p,s)=>part(new THREE.SphereGeometry(1,32,20),m,p,s);
 sphere(green,[0,.76,0],[.51,.56,.35]);sphere(cream,[0,1.5,0],[.65,.57,.46]);sphere(glass,[0,1.48,.36],[.49,.29,.19]);
 for(const x of [-.21,.21]){sphere(mat('#d9f589'),[x,1.52,.537],[.075,.1,.035]);sphere(cream,[x,.18,.08],[.19,.18,.28]);sphere(green,[x*2.7,.82,0],[.16,.33,.18]);sphere(dark,[x*2.7,.55,.035],[.13,.14,.15]);}
 part(new THREE.CylinderGeometry(.035,.035,.31,12),gold,[.27,2.08,0]);sphere(orange,[.27,2.27,0],[.1,.1,.1]);sphere(orange,[-.55,1.46,0],[.14,.2,.19]);sphere(orange,[.55,1.46,0],[.14,.2,.19]);
 part(new THREE.BoxGeometry(.5,.54,.23),orange,[0,.93,-.35]);part(new THREE.BoxGeometry(.36,.08,.04),cream,[0,1,-.485]);part(new THREE.BoxGeometry(.36,.08,.04),cream,[0,.85,-.485]);
 sphere(gold,[0,.91,.344],[.125,.125,.05]);g.userData={note:'Original static test collectible. No skeleton and no animation clips.'};return g;}
function dispose(object){object?.traverse(o=>{o.geometry?.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material])if(m){for(const v of Object.values(m))if(v?.isTexture)v.dispose();m.dispose()}})}
function normalize(object){object.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(object),size=box.getSize(new THREE.Vector3());if(!Number.isFinite(size.length())||size.length()<.00001)throw Error('Das Modell enthält keine sichtbare Geometrie.');const center=box.getCenter(new THREE.Vector3()),scale=2.22/Math.max(size.x,size.y,size.z);const wrapper=new THREE.Group();object.position.sub(new THREE.Vector3(center.x,box.min.y,center.z));wrapper.add(object);wrapper.scale.setScalar(scale);return wrapper;}
function busy(value){$('#export').disabled=value||!ready;for(const selector of ['#import','#reset','#resolution','#palette','#outline','#download-model','#play-adventure','#play-ruins','#store-asset','#asset-usage','#camera','#figure-size','#front','#set-front','#reset-look',...Object.keys(pixelStyles).map(id=>'[data-style='+id+']'),...examples.map(e=>'#example-'+e.id)]){const el=$(selector);if(el)el.disabled=value;}}
async function loadBytes(bytes,name){busy(true);try{const started=performance.now();const manager=new THREE.LoadingManager();manager.setURLModifier(url=>{if(/^(blob:|data:)/.test(url))return url;throw Error('Bitte ein GLB mit eingebetteten Texturen verwenden. Externe Dateien werden nicht geladen.');});const gltf=await new GLTFLoader(manager).parseAsync(bytes,'');let triangles=0,meshes=0,rigged=false;const textures=new Set();gltf.scene.traverse(o=>{if(o.isMesh){meshes++;triangles+=(o.geometry.index?.count??o.geometry.attributes.position.count)/3;rigged ||= Boolean(o.isSkinnedMesh);for(const m of Array.isArray(o.material)?o.material:[o.material])for(const v of Object.values(m))if(v?.isTexture)textures.add(v.uuid)}});if(activeExample?.yaw)gltf.scene.rotation.y+=activeExample.yaw;const next=normalize(gltf.scene);if(model){pivot.remove(model);dispose(model)}model=next;pivot.add(model);modelBytes=bytes;sourceName=name;const usageSuggestion=suggestUsage(name,rigged,activeExample?.usage??(activeExample?'character':undefined));$('#asset-usage').value=usageSuggestion.usage;$('#usage-suggestion').textContent=usageSuggestion.reason+' Du entscheidest. Jedes Modell bleibt spielbar.';modelInfo={bytes:bytes.byteLength,triangles:Math.round(triangles),meshes,textures:textures.size,rigged,sourceClips:gltf.animations.map(a=>a.name),importMs:Math.round(performance.now()-started)};$('#model-name').textContent=name;$('#rig-tag').textContent=rigged?'RIG · RUHEPOSE':'3D · OHNE RIG';appearance.front=0;$('#front').value='0';setDirection(0);await bake();}finally{busy(false)}}

function pose(angle,type,phase){pivot.rotation.set(0,angle+appearance.front*Math.PI/180,0);pivot.position.set(0,0,0);pivot.scale.setScalar(appearance.size/100);if(type==='float'){pivot.position.y=.10+.08*Math.sin(phase*TAU);pivot.rotation.z=.035*Math.sin(phase*TAU)}if(type==='hop'){pivot.position.y=.23*Math.max(0,Math.sin(phase*TAU));pivot.rotation.z=.045*Math.sin(phase*TAU)}}
let renderSize=0; function render(size,angle,type,phase){if(renderSize!==size){renderer.setSize(size,size,false);renderSize=size;}pose(angle,type,phase);renderer.render(scene,camera);}
function processFrame(size){const c=document.createElement('canvas');c.width=c.height=size;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(renderer.domElement,0,0);const im=x.getImageData(0,0,size,size),a=im.data,original=new Uint8ClampedArray(a);const quant=$('#palette').value==='soft';const outline=$('#outline').checked;const ink=pixelStyles[appearance.style].outline;for(let y=0;y<size;y++)for(let xx=0;xx<size;xx++){const i=(y*size+xx)*4;if(a[i+3]>80){a[i+3]=255;if(quant){const color=styleColor(a[i],a[i+1],a[i+2],appearance.style);a[i]=color[0];a[i+1]=color[1];a[i+2]=color[2];}}else{a[i+3]=0;if(outline&&xx>0&&y>0&&xx<size-1&&y<size-1&&[i-4,i+4,i-size*4,i+size*4].some(j=>original[j+3]>80)){a[i]=ink[0];a[i+1]=ink[1];a[i+2]=ink[2];a[i+3]=255}}}x.putImageData(im,0,0);return c;}
// Fit the full motion envelope at the maximum supported size, then retain
// that framing at smaller sizes. This preserves visible size changes and
// reserves transparent margins for every direction, pose and outline.
function configureCamera(){const elevation=cameraPresets[appearance.camera].elevation*Math.PI/180;
 camera.position.set(0,1.1+8*Math.sin(elevation),8*Math.cos(elevation));camera.up.set(0,appearance.camera==='top'?0:1,appearance.camera==='top'?-1:0);camera.lookAt(0,1.1,0);camera.updateMatrixWorld();
 pivot.position.set(0,0,0);pivot.rotation.set(0,0,0);pivot.scale.setScalar(1);pivot.updateMatrixWorld(true);
 const box=new THREE.Box3().setFromObject(model),corners=[];for(const x of [box.min.x,box.max.x])for(const y of [box.min.y,box.max.y])for(const z of [box.min.z,box.max.z])corners.push(new THREE.Vector3(x,y,z));
 const savedSize=appearance.size;appearance.size=120;let minX=Infinity,maxX=-Infinity,minY=Infinity,maxY=-Infinity;
 for(let d=0;d<8;d++)for(const m of motions)for(let f=0;f<frames;f++){pose(d*Math.PI/4,m,f/frames);pivot.updateMatrixWorld(true);for(const point of corners){const p=point.clone().applyMatrix4(pivot.matrixWorld).applyMatrix4(camera.matrixWorldInverse);minX=Math.min(minX,p.x);maxX=Math.max(maxX,p.x);minY=Math.min(minY,p.y);maxY=Math.max(maxY,p.y);}}
 appearance.size=savedSize;const cx=(minX+maxX)/2,cy=(minY+maxY)/2,half=Math.max(maxX-minX,maxY-minY)/2*(1+6/48);
 camera.left=cx-half;camera.right=cx+half;camera.top=cy+half;camera.bottom=cy-half;camera.updateProjectionMatrix();const ground=new THREE.Vector3(0,0,0).project(camera);anchor.x=(ground.x+1)/2;anchor.y=(1-ground.y)/2;
 pose(sourceAngle,'still',0);
}

async function bake(){if(!model)return;const token=++generation;const bakeStart=performance.now();busy(true);baking=true;ready=false;$('#export').disabled=true;resolution=Number($('#resolution').value);configureCamera();$('#appearance-status').textContent='Vorschau wird aktualisiert …';const next=[];const nextSheet=document.createElement('canvas');nextSheet.width=resolution*frames;nextSheet.height=resolution*8*motions.length;const sx=nextSheet.getContext('2d');for(let m=0;m<motions.length;m++){next[m]=[];for(let d=0;d<8;d++){if(token!==generation)return;next[m][d]=[];for(let f=0;f<frames;f++){render(resolution,d*Math.PI/4,motions[m],f/frames);const c=processFrame(resolution);next[m][d].push(c);sx.drawImage(c,f*resolution,(m*8+d)*resolution)}status(`Übersetze ${sourceName} … ${Math.round(((m*8+d+1)/24)*100)} %`);await new Promise(r=>requestAnimationFrame(r));}}if(token!==generation)return;lastSourceAngle=null;atlas=next;sheet=nextSheet;baking=false;ready=true;$('#export').disabled=false;$('#pixel-tag').textContent=`${resolution} × ${resolution} PX`;status(`Bereit · 8 Richtungen · 3 Bewegungen · ${frames*8*3} Frames · ohne Rig oder KI-Rekonstruktion.`);bakeMilliseconds=Math.round(performance.now()-bakeStart);busy(false);updateModelDetails();$('#appearance-status').textContent=cameraPresets[appearance.camera].label+' · '+appearance.size+' % · '+($('#palette').value==='soft'?pixelStyles[appearance.style].label:'Originalfarben')+' · Vorschau und Export sind synchron.';$('#world-view').textContent=' / '+cameraPresets[appearance.camera].label;document.querySelector('.world-help').textContent=appearance.camera==='side'?'Maus / Touch: Ziel wählen · Tastatur: A/D oder ←/→':'Maus / Touch: Ziel wählen · Tastatur: WASD / Pfeile';world.setAttribute('aria-label',appearance.camera==='side'?'Spielszene. Klicken oder tippen zum Bewegen. Tastatur: A/D oder Pfeile links/rechts.':'Spielszene. Klicken oder tippen zum Bewegen. Tastatur: WASD oder Pfeiltasten.');window.lab.ready=true;}
function setDirection(d){direction=(d+8)%8;sourceAngle=direction*Math.PI/4;$('#direction-label').textContent=names[direction];document.querySelectorAll('.directions button').forEach((b,i)=>{b.classList.toggle('active',i===direction);b.setAttribute('aria-pressed',String(i===direction))})}
['↓','↘','→','↗','↑','↖','←','↙'].forEach((arrow,i)=>{const b=document.createElement('button');b.textContent=arrow;b.title=names[i];b.setAttribute('aria-label',names[i]);b.onclick=()=>setDirection(i);$('#directions').append(b)});setDirection(0);
for(const el of ['#resolution','#palette','#outline'])$(el).onchange=()=>bake();
function syncAppearanceControls(){$('#camera').value=appearance.camera;$('#figure-size').value=appearance.size;$('#size-value').value=appearance.size+' %';$('#front').value=appearance.front;document.querySelectorAll('[data-style]').forEach(b=>{b.classList.toggle('active',b.dataset.style===appearance.style);b.setAttribute('aria-pressed',String(b.dataset.style===appearance.style))})}
$('#camera').onchange=()=>{appearance.camera=$('#camera').value;target.x=player.x;target.y=player.y;setDirection(appearance.camera==='side'?2:0);bake()};
$('#figure-size').oninput=()=>$('#size-value').value=$('#figure-size').value+' %';
$('#figure-size').onchange=()=>{appearance.size=Number($('#figure-size').value);bake()};
$('#front').onchange=()=>{appearance.front=Number($('#front').value);setDirection(0);bake()};
$('#set-front').onclick=()=>{appearance.front=(appearance.front+direction*45)%360;setDirection(0);syncAppearanceControls();bake()};
for(const b of document.querySelectorAll('[data-style]'))b.onclick=()=>{appearance.style=b.dataset.style;$('#palette').value='soft';syncAppearanceControls();bake()};
$('#reset-look').onclick=()=>{Object.assign(appearance,{camera:'iso',size:100,front:0,style:'studio'});$('#resolution').value='64';$('#palette').value='soft';$('#outline').checked=true;setDirection(0);syncAppearanceControls();bake()};
for(const b of document.querySelectorAll('[data-motion]'))b.onclick=()=>{motion=b.dataset.motion;elapsed=0;document.querySelectorAll('[data-motion]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))})};
$('#pause').onclick=()=>{paused=!paused;$('#pause').textContent=paused?'▶ Weiter':'Ⅱ Pause';$('#pause').setAttribute('aria-pressed',String(paused))};
let drag=null;sourceCanvas.onpointerdown=e=>{if(baking)return;drag={x:e.clientX,a:sourceAngle};sourceCanvas.setPointerCapture(e.pointerId)};sourceCanvas.onpointermove=e=>{if(drag&&!baking){sourceAngle=drag.a+(e.clientX-drag.x)*.015;setDirection(Math.round(sourceAngle/(Math.PI/4)))}};sourceCanvas.onpointerup=sourceCanvas.onpointercancel=()=>drag=null;
const player={x:480,y:224},target={...player},keys=new Set();world.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(e.key)){keys.add(e.key);e.preventDefault()}});world.addEventListener('keyup',e=>keys.delete(e.key));world.addEventListener('blur',()=>keys.clear());window.addEventListener('blur',()=>keys.clear());
world.onpointerdown=e=>{world.focus({preventScroll:true});const rect=world.getBoundingClientRect();target.x=Math.max(180,Math.min(780,(e.clientX-rect.left)/rect.width*960));target.y=Math.max(163,Math.min(287,(e.clientY-rect.top)/rect.height*360))};
function rect(x,y,w,h,color){ctx.fillStyle=color;ctx.fillRect(x,y,w,h)}
function poly(points,color){ctx.fillStyle=color;ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.fill()}
function tree(x,y,s=1){rect(x-4*s,y-8*s,8*s,38*s,'#8b9070');rect(x-27*s,y-35*s,54*s,35*s,'#43644c');rect(x-19*s,y-51*s,38*s,22*s,'#68835b');rect(x-10*s,y-60*s,20*s,12*s,'#92a36b');rect(x-27*s,y-8*s,54*s,8*s,'#294b40')}
function drawWorld(t){if(appearance.camera==='iso'){ctx.clearRect(0,0,960,360);rect(0,0,960,360,'#193b32');for(let i=0;i<42;i++){const x=(i*137+57)%960,y=(i*73+27)%350;rect(x,y,2,2,i%3?'#42604a':'#829665')}
 poly([[131,167],[657,132],[841,183],[828,294],[311,329],[130,279]],'#102c29');poly([[131,157],[657,122],[841,173],[828,277],[311,310],[130,261]],'#5e7953');poly([[131,157],[657,122],[841,173],[322,222]],'#8fa575');poly([[131,157],[322,222],[311,294],[130,246]],'#6b8558');poly([[322,222],[841,173],[828,264],[311,294]],'#819c65');
 poly([[184,195],[712,165],[760,198],[220,244]],'#aeba89');poly([[382,155],[437,150],[595,266],[542,273]],'#aeba89');
 for(let i=0;i<48;i++){const x=160+(i*97)%650,y=167+(i*47)%104;rect(x,y,4,2,'#738f5c')}
 rect(588,104,134,63,'#c7cca5');poly([[577,107],[648,74],[739,100],[669,126]],'#384e41');poly([[669,126],[739,100],[739,110],[669,136]],'#243e34');rect(612,127,23,40,'#496344');rect(672,133,29,21,'#6f8b67');rect(675,135,23,3,'#bfd78e');rect(650,120,7,37,'#a8b68b');
 tree(193,161,1.05);tree(286,128,.8);tree(763,169,.85);tree(809,238,.65);tree(154,251,.55);
 rect(364,239,39,6,'#d1c599');rect(366,245,4,10,'#60744d');rect(396,245,4,10,'#60744d');
 for(const [x,y] of [[241,177],[732,230],[437,277],[330,162],[695,254]]){rect(x,y,3,9,'#46664b');rect(x-2,y-2,7,4,'#e6c380')}
 }else if(appearance.camera==='side'){
 rect(0,0,960,360,'#18372f');for(let i=0;i<22;i++)rect((i*137+50)%960,40+(i*53)%155,2,2,'#68856b');
 poly([[0,225],[90,168],[177,216],[297,143],[430,229],[580,160],[719,226],[854,163],[960,220],[960,360],[0,360]],'#315540');
 rect(110,266,740,16,'#a7bb7e');rect(110,282,740,42,'#698750');rect(122,312,715,13,'#375c3f');for(let i=0;i<25;i++)rect(126+i*29,286+(i%3)*7,5,4,'#81985e');
 tree(172,211,.7);tree(785,212,.7);rect(632,194,91,72,'#c4cba2');poly([[620,198],[678,158],[735,198]],'#3f5b42');rect(665,225,22,41,'#38563f');rect(708,212,8,11,'#9bb776');
 }else{
 rect(0,0,960,360,'#183b32');rect(137,94,688,227,'#365b40');rect(145,86,672,226,'#849e68');rect(172,172,618,36,'#bdc695');rect(438,105,48,182,'#bdc695');
 for(let i=0;i<55;i++)rect(163+(i*113)%631,104+(i*41)%189,3,3,'#78935e');
 for(const [x,y] of [[190,124],[745,125],[190,265],[748,267]]){rect(x-21,y-18,43,36,'#426845');rect(x-13,y-23,26,44,'#71935b');rect(x-8,y-14,18,20,'#9ab878');}
 rect(604,102,103,57,'#3b5a41');rect(609,108,93,47,'#ced1a0');rect(618,114,75,34,'#758a5b');rect(650,150,18,11,'#b2bd89');
 }
 const drawY=appearance.camera==='side'?266:player.y;
 const dist=Math.hypot(target.x-player.x,appearance.camera==='side'?0:target.y-player.y);if(dist>3){ctx.strokeStyle='#e3efb2';ctx.lineWidth=1;ctx.beginPath();ctx.ellipse(target.x,appearance.camera==='side'?266:target.y,10,4,0,0,TAU);ctx.stroke();rect(target.x-1,(appearance.camera==='side'?266:target.y)-2,2,4,'#e3efb2')}
 if(ready){const frame=atlas[motions.indexOf(motion)][direction][Math.floor(t*fps)%frames],scale=128/resolution;ctx.imageSmoothingEnabled=false;ctx.fillStyle='#203c3260';ctx.beginPath();ctx.ellipse(player.x,drawY,22*appearance.size/100,7*appearance.size/100,0,0,TAU);ctx.fill();ctx.drawImage(frame,Math.round(player.x-resolution*scale*anchor.x),Math.round(drawY-resolution*scale*anchor.y),resolution*scale,resolution*scale)}
}
let lastSourceAngle=null,lastSourceWidth=0,lastSourceHeight=0; function tick(ms){const dt=Math.min(.05,(ms-last)/1000||0);last=ms;if(!paused)elapsed+=dt;if(!paused&&ready){let dx=(keys.has('d')||keys.has('ArrowRight')?1:0)-(keys.has('a')||keys.has('ArrowLeft')?1:0),dy=(keys.has('s')||keys.has('ArrowDown')?1:0)-(keys.has('w')||keys.has('ArrowUp')?1:0);if(appearance.camera==='side')dy=0;const keyboard=dx||dy;if(!keyboard){dx=target.x-player.x;dy=appearance.camera==='side'?0:target.y-player.y}const dist=Math.hypot(dx,dy);if(dist>.8){const step=Math.min(keyboard?Infinity:dist,100*dt);player.x=Math.max(180,Math.min(780,player.x+dx/dist*step));player.y=Math.max(163,Math.min(287,player.y+dy/dist*step));if(keyboard){target.x=player.x;target.y=player.y}setDirection(Math.round(Math.atan2(dx,dy)/(Math.PI/4)))}}
 if(model&&!baking){const w=Math.round(sourceCanvas.clientWidth),h=Math.round(sourceCanvas.clientHeight);if(sourceCanvas.width!==w||sourceCanvas.height!==h){sourceCanvas.width=w;sourceCanvas.height=h}if(sourceAngle!==lastSourceAngle||w!==lastSourceWidth||h!==lastSourceHeight){lastSourceAngle=sourceAngle;lastSourceWidth=w;lastSourceHeight=h;render(420,sourceAngle,'still',0);sourceCtx.clearRect(0,0,w,h);sourceCtx.imageSmoothingEnabled=true;sourceCtx.drawImage(renderer.domElement,(w-h)/2,-6,h,h);}}
 if(ready){pixelCtx.clearRect(0,0,320,256);pixelCtx.imageSmoothingEnabled=false;const frame=atlas[motions.indexOf(motion)][direction][Math.floor(elapsed*fps)%frames],scale=192/resolution;pixelCtx.drawImage(frame,(320-resolution*scale)/2,(256-resolution*scale)/2,resolution*scale,resolution*scale)}drawWorld(elapsed);requestAnimationFrame(tick)}
function download(bytes,name,type='application/octet-stream'){const url=URL.createObjectURL(new Blob([bytes],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}
function metadata(){return{format:'form-pixel/2',assetUsage:$('#asset-usage').value,appearance:{...appearance,palette:$('#palette').value,outline:$('#outline').checked},source:sourceName,sourceInfo:modelInfo,sourceLicense:activeExample?.license??'Vom Importierenden zu klären',bakeMilliseconds,frameWidth:resolution,frameHeight:resolution,columns:frames,rows:24,fps,anchor,directions:names,animationType:'whole-object procedural motion; no skeletal rig',animations:Object.fromEntries(motions.map((name,i)=>[name,{firstRow:i*8,directions:8,framesPerDirection:frames,loop:true}]))}}
$('#export').onclick=async()=>{busy(true);try{const blob=await new Promise(r=>sheet.toBlob(r,'image/png'));const godot=`extends Sprite2D\n# Attach to a Sprite2D with sprites.png as texture. Use nearest filtering.\n# Rows: still 0-7, float 8-15, hop 16-23. Directions start at front.\n@export_range(0, 7) var direction: int = 0\n@export_enum("Still", "Float", "Hop") var motion: int = 1\nvar clock: float = 0.0\nfunc _ready() -> void:\n\thframes = 12\n\tvframes = 24\n\ttexture_filter = CanvasItem.TEXTURE_FILTER_NEAREST\n\tcentered = false\n\toffset = Vector2(-${(resolution*anchor.x).toFixed(4)}, -${(resolution*anchor.y).toFixed(4)})\nfunc _process(delta: float) -> void:\n\tclock += delta\n\tframe_coords = Vector2i(int(clock * 12.0) % 12, motion * 8 + direction)\n`;
 const readme='FORM / PIXEL export\n\nLoad sprites.png with nearest-neighbor filtering. Each row is one direction; columns are animation frames. See animations.json for frame size, timing and foot anchor. Direction order: front, front-right, right, back-right, back, back-left, left, front-left.\n\nGodot 4: create a Sprite2D, assign sprites.png as texture and collectible.gd as script. Set motion 0/1/2 and direction 0-7. The node position is the ground contact point.\n\nAnimations move/tilt the whole object. No skeleton, walking cycle or AI reconstruction is generated. Source rights remain unchanged.\n';
 const creditFiles=Object.fromEntries(Object.entries(licenseDocs).map(([name,content])=>['licenses/'+name,strToU8(content)]));
 download(zipSync({...creditFiles,'CREDITS.txt':strToU8(creditText()),'sprites.png':new Uint8Array(await blob.arrayBuffer()),'animations.json':strToU8(JSON.stringify(metadata(),null,2)),'collectible.gd':strToU8(godot),'README.txt':strToU8(readme)}),'form-pixel-gamepack.zip','application/zip');status('Spielpaket exportiert · PNG + JSON + Godot-Script.')}catch(e){status('Export fehlgeschlagen: '+e.message)}finally{busy(false)}};
$('#download-model').onclick=()=>{if(!modelBytes)return;if(activeExample?.docs){download(zipSync({[activeExample.id+'.glb']:new Uint8Array(modelBytes),'CREDITS.txt':strToU8(creditText()),...Object.fromEntries(Object.entries(licenseDocs).map(([name,content])=>['licenses/'+name,strToU8(content)]))}),activeExample.id+'-source.zip','application/zip')}else download(modelBytes,(activeExample?.id??'imported')+'-static.glb','model/gltf-binary')};
$('#import').onclick=()=>$('#file').click();
$('#file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>40*1024*1024)throw Error('Bitte ein GLB kleiner als 40 MB wählen.');if(!file.name.toLowerCase().endsWith('.glb'))throw Error('Dieses Experiment unterstützt GLB-Dateien.');status('Modell wird gelesen …');const priorExample=activeExample,priorDocs=licenseDocs;activeExample=null;licenseDocs={};try{await loadBytes(await file.arrayBuffer(),file.name)}catch(e){activeExample=priorExample;licenseDocs=priorDocs;throw e}}catch(err){status('Import nicht möglich: '+err.message+' Das bisherige Modell bleibt verfügbar.')}finally{e.target.value=''}};
$('#reset').onclick=()=>chooseExample('momo');
window.lab={get ready(){return ready},set ready(v){ready=v},metadata,get sheet(){return sheet},get player(){return {...player}},get direction(){return direction},get motion(){return motion},get modelBytes(){return modelBytes},get activeExample(){return activeExample?.id},get modelInfo(){return modelInfo},get appearance(){return {...appearance}}};
function creditText(){return `FORM / PIXEL — ${sourceName}\n${activeExample?.license??'User-provided model. Rights remain with its author.'}\n${activeExample?.source??'Original FORM / PIXEL workshop example or user-provided asset.'}\nChanges: normalized scale, orthographic rendering from eight horizontal directions, optional color quantization and outlines, whole-object motion. Original animation clips were not played. Original model geometry and textures are otherwise unchanged.\nCC BY 4.0: https://creativecommons.org/licenses/by/4.0/\nNo endorsement by the original authors is implied. See included license documents.\n`;}
function updateModelDetails(){$('#download-model').textContent=activeExample?.docs?'3D-Modell + Lizenz (.zip) ↓':'3D-Modell (.glb) ↓';const info=modelInfo;$('#model-stats').textContent=`${(info.bytes/1024).toFixed(0)} KB GLB · ${info.triangles.toLocaleString('de-DE')} Dreiecke · ${info.textures} Texturen · ${info.sourceClips.length} Quellanimationen (nicht abgespielt) · Umwandlung ${(bakeMilliseconds/1000).toFixed(2)} s auf diesem Gerät`;
 document.querySelectorAll('.example-card').forEach(b=>{const selected=b.dataset.example===activeExample?.id;b.classList.toggle('active',selected);b.setAttribute('aria-pressed',String(selected))});const credit=$('#asset-credit');credit.replaceChildren();credit.append(document.createTextNode(activeExample?.license??'Eigenes Modell · Rechte und Quelle beim Urheber.'));if(activeExample?.source){const a=document.createElement('a');a.href=activeExample.source;a.textContent=' · Quelle & Lizenz ↗';a.target='_blank';a.rel='noopener';credit.append(a)}if(activeExample){const c=$('#example-'+activeExample.id+' canvas');if(c){const x=c.getContext('2d');x.clearRect(0,0,128,128);x.imageSmoothingEnabled=false;x.drawImage(atlas[0][1][0],0,0,128,128)}}}
const byteCache=new Map();
async function chooseExample(id){if(baking)return;const example=examples.find(e=>e.id===id);if(!example)return;busy(true);status(example.name+' wird geladen …');const previous=activeExample,previousDocs=licenseDocs;try{if(!byteCache.has(id)){if(example.url){const response=await fetch(example.url);if(!response.ok)throw Error('Beispieldatei fehlt.');byteCache.set(id,await response.arrayBuffer());}else{const original=id==='momo'?testModel():createExample(id);byteCache.set(id,await new GLTFExporter().parseAsync(original,{binary:true}));dispose(original)}}const docs=await Promise.all((example.docs??[]).map(async name=>{const r=await fetch('./assets/'+name);if(!r.ok)throw Error('Lizenzdatei fehlt.');return [name,await r.text()]}));activeExample=example;licenseDocs=Object.fromEntries(docs);await loadBytes(byteCache.get(id),example.name+' / '+example.type);if(id==='momo')testBytes=modelBytes;}catch(e){activeExample=previous;licenseDocs=previousDocs;status('Beispiel konnte nicht geladen werden: '+e.message);console.error(e)}finally{busy(false)}}
for(const example of examples){const b=document.createElement('button');b.className='example-card';b.id='example-'+example.id;b.dataset.example=example.id;b.setAttribute('aria-label',example.name+' testen');const c=document.createElement('canvas');c.width=c.height=128;c.setAttribute('aria-hidden','true');const x=c.getContext('2d');x.fillStyle='#dbe4cc';x.font='bold 34px monospace';x.textAlign='center';x.fillText(example.name.slice(0,2),64,78);const title=document.createElement('strong');title.textContent=example.name;const note=document.createElement('small');note.textContent=example.note;const thumb=new Image();thumb.onload=()=>{x.clearRect(0,0,128,128);x.imageSmoothingEnabled=false;x.drawImage(thumb,0,0,128,128)};if(example.preview!==false)thumb.src='./assets/previews/'+example.id+'.png';b.append(c,title,note);b.onclick=()=>chooseExample(example.id);$('#examples').append(b);}
const feedbackKey='form-pixel-feedback-v1';
function readFeedback(){try{const value=JSON.parse(localStorage.getItem(feedbackKey)??'[]');return Array.isArray(value)?value:[]}catch{return []}}
function updateFeedbackCount(){$('#feedback-count').textContent=readFeedback().length+' Rückmeldungen auf diesem Gerät';}
$('#open-feedback').onclick=()=>{$('#feedback-status').textContent='';$('#feedback-dialog').showModal()};$('#close-feedback').onclick=()=>$('#feedback-dialog').close();
$('#feedback-form').onsubmit=e=>{e.preventDefault();const form=new FormData(e.target),message=String(form.get('message')).trim();if(message.length<8){$('#feedback-status').textContent='Bitte beschreibe kurz, was du beobachtet hast (mindestens 8 Zeichen).';return}const record={id:crypto.randomUUID(),createdAt:new Date().toISOString(),version:'0.6',kind:form.get('kind'),success:form.get('success'),rating:form.get('rating')?Number(form.get('rating')):null,message,useCase:String(form.get('useCase')).trim(),context:{appearance:{...appearance},example:activeExample?.id??'user-import',resolution,palette:$('#palette').value,outline:$('#outline').checked,motion,direction,rigged:modelInfo.rigged,bakeMilliseconds},delivery:'local-only-not-sent'};try{const records=readFeedback();records.push(record);localStorage.setItem(feedbackKey,JSON.stringify(records));$('#feedback-status').textContent='Lokal gespeichert. Zum Teilen kannst du unten einen GitHub-Entwurf prüfen.';updateFeedbackCount()}catch{$('#feedback-status').textContent='Speichern ist in diesem Browser nicht möglich. Dein Text bleibt im Formular.'}};
$('#export-feedback').onclick=()=>{const records=readFeedback();if(!records.length){status('Noch keine Rückmeldungen auf diesem Gerät. Über „Feedback geben“ kannst du beginnen.');return}download(JSON.stringify({format:'form-pixel-feedback/1',exportedAt:new Date().toISOString(),records},null,2),'form-pixel-feedback.json','application/json');status('Feedback-Datei exportiert. Es wurde nichts automatisch versendet.');};updateFeedbackCount();
// The isolated film page uses the same renderer and sprite pipeline as the tool.
if(new URLSearchParams(location.search).has('film'))window.filmEngine={
 async prepare(){
  while(!ready)await new Promise(r=>setTimeout(r,50));
  const captures={},turntable=[];appearance.size=120;$('#resolution').value='64';
  for(const style of ['studio','pocket','arcade']){appearance.style=style;await bake();captures[style]=atlas;}
  appearance.style='studio';await bake();
  for(let n=0;n<72;n++){render(480,n/72*TAU,'still',0);const c=document.createElement('canvas');c.width=c.height=480;c.getContext('2d').drawImage(renderer.domElement,0,0);turntable.push(c)}
  const figures={momo:captures.studio};
  for(const id of ['orbit','bloom']){await chooseExample(id);figures[id]=atlas;}
  await chooseExample('momo');
  return{captures,turntable,figures};
 },
 world(t){motion='hop';player.x=330+t*78;player.y=235+Math.sin(t*1.5)*18;target.x=player.x;target.y=player.y;direction=t<2?2:1;drawWorld(t);return world;}
};
async function start(){await chooseExample(new URLSearchParams(location.search).has('film')?'momo':'dragon');if(!new URLSearchParams(location.search).has('film'))requestAnimationFrame(tick)}start();

const adventureDialog=$('#adventure-dialog'),adventureFrame=$('#adventure-frame');
async function launchAdventure(route){if(!ready||baking)return;try{if(appearance.camera!=='iso'){appearance.camera='iso';syncAppearanceControls();await bake()}
 const payload={type:'form-pixel-adventure',sheet:sheet.toDataURL('image/png'),metadata:metadata(),name:activeExample?.name??sourceName,credit:activeExample?.license??'Eigenes importiertes Modell'};
 try{sessionStorage.setItem('form-pixel-adventure',JSON.stringify(payload))}catch{}
 adventureFrame.onload=()=>adventureFrame.contentWindow.postMessage(payload,location.origin);adventureFrame.src=route;adventureDialog.showModal();
}catch(e){status('Spielprobe konnte nicht starten: '+e.message)}};
$('#play-adventure').onclick=()=>launchAdventure('./heimkehr.html');
$('#play-ruins').onclick=()=>launchAdventure('./ruins.html');
window.addEventListener('message',e=>{if(e.origin===location.origin&&e.source===adventureFrame.contentWindow&&e.data?.type==='adventure-exit')adventureDialog.close()});
adventureDialog.addEventListener('close',()=>{adventureFrame.contentWindow?.postMessage({type:'adventure-close'},location.origin);adventureFrame.src='about:blank';$('#play-adventure').focus()});
// Explicit local asset capture page; absent from the normal workshop.
if(new URLSearchParams(location.search).has('capture')){const b=document.createElement('button');b.id='capture-preview';b.textContent='Vorschaubild speichern';document.querySelector('.collection').append(b);b.onclick=async()=>{if(!ready)return;const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d');x.imageSmoothingEnabled=false;x.drawImage(atlas[0][1][0],0,0,128,128);const blob=await new Promise(r=>c.toBlob(r));const i=examples.findIndex(e=>e.id===activeExample?.id);const response=await fetch('/frame/'+String(9000+i),{method:'POST',body:blob});b.textContent=response.ok?'Vorschaubild gespeichert':'Fehler beim Speichern';}};


function readShelf(){try{const items=JSON.parse(sessionStorage.getItem('form-pixel-props')||'[]');return Array.isArray(items)?items.slice(0,3):[]}catch{return []}}
function showShelf(){const shelf=$('#asset-shelf');shelf.replaceChildren();for(const [i,item] of readShelf().entries()){const box=document.createElement('div'),name=document.createElement('span'),remove=document.createElement('button');name.textContent=item.name+' · '+(item.metadata.assetUsage==='equipment'?'Ausrüstung':item.metadata.assetUsage==='object'?'Gegenstand':'Figur als Statue');remove.textContent='Entfernen';remove.className='text-button';remove.onclick=()=>{const items=readShelf();items.splice(i,1);try{sessionStorage.setItem('form-pixel-props',JSON.stringify(items));showShelf()}catch{$('#shelf-status').textContent='Ablage konnte nicht gespeichert werden.'}};box.append(name,remove);shelf.append(box)}}
$('#store-asset').onclick=async()=>{if(!ready||baking)return;try{if(appearance.camera!=='iso'){appearance.camera='iso';syncAppearanceControls();await bake()}const item={type:'form-pixel-adventure',sheet:sheet.toDataURL('image/png'),metadata:metadata(),name:activeExample?.name??sourceName,credit:activeExample?.license??'Eigenes Modell'};const items=readShelf().filter(p=>p.metadata.source!==item.metadata.source);if(items.length>=3){$('#shelf-status').textContent='Die drei Plätze sind belegt. Entferne zuerst einen Gegenstand.';return}items.push(item);sessionStorage.setItem('form-pixel-props',JSON.stringify(items));showShelf();$('#shelf-status').textContent='Abgelegt. Wähle jetzt deinen Helden und öffne die lebende Ruine. Ausrüstung wird zusätzlich an der Figur angezeigt.'}catch(e){$('#shelf-status').textContent='Ablage konnte nicht gespeichert werden: '+e.message}};showShelf();


$('#preview-feedback').onclick=()=>{const form=$('#feedback-form');if(!form.reportValidity())return;const data=new FormData(form);try{const draft=buildFeedbackIssue({kind:data.get('kind'),message:data.get('message'),useCase:data.get('useCase'),success:data.get('success'),context:{camera:appearance.camera,style:appearance.style,resolution,customModel:!activeExample}});$('#issue-preview-text').textContent=draft.body;$('#issue-link').href=draft.url;$('#issue-preview').hidden=false;$('#issue-link').focus()}catch(error){$('#feedback-status').textContent=error.message}};
$('#feedback-form').addEventListener('input',()=>{$('#issue-preview').hidden=true;$('#issue-link').removeAttribute('href')});

