import {TILE,W,H,map,rooms,pillars,runes,gate,spawn,createRun,pathTo,step,dash,sentinels} from './dungeon-core.js';
const $=s=>document.querySelector(s),canvas=$('#dungeon'),ctx=canvas.getContext('2d'),keys=new Set();
let run=createRun(),sheet=null,meta=null,cam={x:0,y:0},last=0,fx=[],toastTimer=0,paused=false,gameName='Reisender',soundCtx,trail=[],clock=0;
const rand=(x,y)=>{const n=Math.sin(x*127.1+y*311.7)*43758.5453;return n-Math.floor(n)};
const rect=(x,y,w,h,c)=>{ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),w,h)};
function poly(points,c){ctx.fillStyle=c;ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.fill()}
function glow(x,y,r,c){const g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,c);g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.fillRect(x-r,y-r,r*2,r*2)}
function speak(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3500)}
function chime(notes){if(!$('#sound').checked)return;try{soundCtx??=new AudioContext();soundCtx.resume();notes.forEach((hz,i)=>{const o=soundCtx.createOscillator(),g=soundCtx.createGain(),t=soundCtx.currentTime+i*.09;o.type='sine';o.frequency.value=hz;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.065,t+.012);g.gain.exponentialRampToValueAtTime(.001,t+.42);o.connect(g).connect(soundCtx.destination);o.start(t);o.stop(t+.44)})}catch{}}
function burst(x,y,color,count=22){for(let i=0;i<count;i++){const a=i/count*Math.PI*2;fx.push({x,y,vx:Math.cos(a)*(25+i%6*9),vy:Math.sin(a)*(25+i%5*9)-20,life:.7+i%4*.15,max:1.2,color})}}
function hud(){const n=run.collected.length;$('#runes').replaceChildren(document.createTextNode('◆ '.repeat(n)+'◇ '.repeat(3-n)));const small=document.createElement('small');small.textContent=n+' / 3 Runensplitter';$('#runes').append(small);$('#chapter').textContent=n===3?'DIE TÜR ERWACHT':run.distance<60?'DEINE ERSTEN SCHRITTE':'DIE VERLORENEN RUNEN';$('#objective').textContent=n===3?'Das Portal leuchtet. Finde die Tür im Südosten.':run.distance<60?'Klicke auf den Boden und setze deinen ersten Schritt.':'Folge den leuchtenden Runen. Dash schützt vor Irrlichtern.';canvas.setAttribute('aria-label',`Dungeon: ${gameName}. ${n} von 3 Runen. Position ${Math.round(run.x)}, ${Math.round(run.y)}. ${run.phase==='won'?'Portal erreicht.':'Klicken zum Laufen, WASD oder Pfeile, Leertaste für Dash.'}`);$('#dash').disabled=run.phase!=='explore'||paused||run.cooldown>0;$('#dash').innerHTML=run.cooldown>0?`✦ ${run.cooldown.toFixed(1)} s<small>lädt auf</small>`:'✦ Dash <small>Leertaste</small>';}
async function accept(data){if(!data||data.type!=='form-pixel-adventure'||typeof data.sheet!=='string'||!data.sheet.startsWith('data:image/png;')||data.sheet.length>20e6)return;const im=new Image();im.src=data.sheet;await im.decode();const m=data.metadata;if(!m||![48,64,96].includes(m.frameWidth)||im.width!==m.frameWidth*12||im.height!==m.frameWidth*24)throw Error('Sprite-Paket ungültig');sheet=im;meta=m;gameName=(data.name||m.source||'Reisender').split(' / ')[0].slice(0,24);$('#character-name').value=gameName;$('#portrait-name').textContent=gameName;$('#hero-name').textContent=gameName;$('#hero-detail').textContent=`${m.frameWidth} px · ${m.appearance?.style??'Studio'} · 8 Richtungen`;$('#credits').textContent=data.credit||'Eigene Figur';$('#begin').disabled=false;}
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent)return;if(e.data?.type==='adventure-close'){paused=true;keys.clear()}else accept(e.data).catch(e=>speak(e.message))});
try{const data=JSON.parse(sessionStorage.getItem('form-pixel-adventure')||'null');if(data)accept(data).catch(e=>speak(e.message));else $('#hero-detail').textContent='Bitte zuerst eine Figur in der Werkstatt wählen.'}catch{}
function back(){keys.clear();paused=true;if(parent!==window)parent.postMessage({type:'adventure-exit'},location.origin);else location.href='./'}
$('#close').onclick=back;$('#finish').onclick=back;
$('#begin').onclick=()=>{if(!sheet)return;gameName=$('#character-name').value.trim()||gameName;$('#hero-name').textContent=gameName;run.phase='explore';$('#intro').hidden=true;canvas.focus();burst(run.x,run.y,'#87e9d1',40);chime([293.66,440,587.33]);speak('Willkommen, '+gameName+'. Die erste Rune wartet im Norden.');hud()};
function restart(){run=createRun();run.phase='explore';paused=false;fx=[];trail=[];$('#ending').hidden=true;$('#pause-panel').hidden=true;canvas.focus();hud()}
$('#again').onclick=restart;
function pause(value){if(run.phase!=='explore')return;paused=value;keys.clear();$('#pause-panel').hidden=!value;$('#pause').textContent=value?'▶ Weiter':'Ⅱ Pause';if(!value)canvas.focus();hud()}
$('#pause').onclick=()=>pause(!paused);$('#resume').onclick=()=>pause(false);window.addEventListener('blur',()=>{keys.clear();if(run.phase==='explore')pause(true)});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause(true)});
function doDash(){if(paused)return;if(dash(run)){burst(run.x,run.y,'#b8eeb7',12);chime([220,440])}canvas.focus()}
$('#dash').onclick=doDash;
window.addEventListener('keydown',e=>{if(e.target.tagName==='INPUT')return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d','W','A','S','D',' '].includes(e.key)){e.preventDefault();if(e.key===' '){if(!e.repeat)doDash()}else keys.add(e.key.toLowerCase())}if(e.key==='Escape')pause(!paused)});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
for(const b of document.querySelectorAll('[data-dir]')){const key={up:'w',left:'a',down:'s',right:'d'}[b.dataset.dir];let downAt=0;b.onclick=()=>{if(run.phase!=='explore'||paused)return;if(performance.now()-downAt<220||downAt===0){const [dx,dy]={w:[0,-32],a:[-32,0],s:[0,32],d:[32,0]}[key];run.path=pathTo(run,{x:run.x+dx,y:run.y+dy})}};b.onpointerdown=e=>{downAt=performance.now();e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(key)};for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>keys.delete(key))}
canvas.addEventListener('pointerdown',e=>{if(run.phase!=='explore'||paused)return;const b=canvas.getBoundingClientRect(),mx=(e.clientX-b.left)*canvas.width/b.width,my=(e.clientY-b.top)*canvas.height/b.height;const onMap=mx>canvas.width-131&&my<102;const dest=onMap?{x:(mx-(canvas.width-122))/2.3*TILE,y:(my-19)/2.3*TILE}:{x:mx+cam.x,y:my+cam.y};const route=pathTo(run,dest);if(route.length){run.path=route;burst(dest.x,dest.y,'#a9d4bd',8)}else speak('Wähle einen Punkt auf dem begehbaren Steinboden.');canvas.focus()});
function floor(){for(let y=0;y<H;y++)for(let x=0;x<W;x++){if(!map[y][x])continue;const X=x*TILE,Y=y*TILE,n=rand(x,y);rect(X,Y,32,32,'#203332');rect(X+1,Y+1,30,29,n>.65?'#344844':n>.3?'#30433f':'#293e3b');rect(X+2,Y+2,28,1,'#46574b');if(n>.62)rect(X+7,Y+19,10,1,'#50604d');if(n<.2){rect(X+23,Y+5,1,10,'#1e3332');rect(X+19,Y+15,5,1,'#1e3332')}if(n>.87){rect(X+3,Y+6,5,3,'#4d6248');rect(X+5,Y+4,2,4,'#627249')}
 if(y===0||!map[y-1][x]){rect(X,Y-28,32,26,'#203135');rect(X+1,Y-31,30,7,'#597067');rect(X+2,Y-23,28,4,'#3e544f');rect(X+3,Y-7,26,2,'#192b2d');if(x%4===0){rect(X+10,Y-22,13,17,'#15272a');rect(X+13,Y-20,7,12,'#2a4140')}}
 if(!map[y+1]?.[x]){rect(X,Y+31,32,12,'#14282c');rect(X,Y+32,32,2,'#48584b')}
 if(!map[y]?.[x-1])rect(X-5,Y,5,32,'#14282b');if(!map[y]?.[x+1])rect(X+32,Y,5,32,'#14282b');}}
function pillar(x,y){const X=x*TILE+16,Y=y*TILE+23;ctx.fillStyle='#07151880';ctx.beginPath();ctx.ellipse(X+17,Y+6,27,11,0,0,Math.PI*2);ctx.fill();rect(X-16,Y-5,32,10,'#556660');rect(X-13,Y-49,26,46,'#4b605a');rect(X+3,Y-49,10,46,'#2f4946');rect(X-10,Y-47,4,39,'#79907b');rect(X-17,Y-55,34,9,'#778c76');rect(X-14,Y-58,28,4,'#a0ac88');rect(X-9,Y-28,17,3,'#263f3c');rect(X-11,Y-20,6,11,'#526d45');}
function torch(x,y,t){glow(x,y-20,80,'#e3a55424');rect(x-3,y-17,6,17,'#745b40');rect(x-5,y-18,10,4,'#b18b50');const k=Math.sin(t*12+x)*3;poly([[x-6,y-21],[x-3,y-35+k],[x,y-28],[x+4,y-40-k],[x+7,y-22]],'#e59753');poly([[x-3,y-21],[x,y-32],[x+4,y-20]],'#f4dc93');}
function rune(r,i,t){if(run.collected.includes(i))return;const bob=Math.sin(t*2.6+i)*3;glow(r.x,r.y-7,62,'#76e5d52c');ctx.strokeStyle='#658c7e';ctx.lineWidth=1;ctx.beginPath();ctx.ellipse(r.x,r.y+3,17,7,0,0,Math.PI*2);ctx.stroke();poly([[r.x,r.y-27+bob],[r.x+8,r.y-13+bob],[r.x,r.y-2+bob],[r.x-8,r.y-13+bob]],'#7edbc7');poly([[r.x,r.y-27+bob],[r.x,r.y-2+bob],[r.x-8,r.y-13+bob]],'#d4f6be');rect(r.x-1,r.y-21+bob,2,8,'#faffdf');}
function portal(t){const {x,y}=gate,open=run.collected.length===3;glow(x,y-28,open?120:45,open?'#a7eabc35':'#6b6c8020');ctx.fillStyle=open?'#3c6860':'#0b1e24';ctx.beginPath();ctx.ellipse(x,y-31,24,38,0,0,Math.PI*2);ctx.fill();for(let i=0;i<7;i++){const a=i/6*Math.PI;const X=x+Math.cos(a)*32,Y=y-24-Math.sin(a)*39;rect(X-7,Y-8,14,16,i%2?'#708174':'#8c967c');if(open)rect(X-2,Y-2,4,5,'#d5f5ad')}for(const sign of[-1,1]){rect(x+sign*30-6,y-26,12,31,'#65776e');rect(x+sign*30-7,y-1,14,6,'#a3ac88')}
 if(open){for(let i=0;i<16;i++){const a=t*1.8+i*.9;rect(x+Math.cos(a)*(8+i*.9),y-27+Math.sin(a)*27,2,4,'#c1f2b3')}ctx.strokeStyle='#a6e7b5';ctx.beginPath();ctx.ellipse(x,y+7,37,12,0,0,Math.PI*2);ctx.stroke()}else for(let i=0;i<3;i++)rect(x-9+i*7,y-33,4,10,run.collected.includes(i)?'#b8e4ab':'#4b6261');}
function hero(){if(!sheet||!meta)return;glow(run.x,run.y-22,56,'#b6d78a16');const n=meta.frameWidth,frame=Math.floor(run.time*12)%12,row=(run.moving?2:1)*8+run.direction,s=128;ctx.fillStyle='#03121790';ctx.beginPath();ctx.ellipse(run.x,run.y,22,8,0,0,Math.PI*2);ctx.fill();if(run.invulnerable>0&&Math.floor(clock*12)%2===0)ctx.globalAlpha=.45;ctx.imageSmoothingEnabled=false;ctx.drawImage(sheet,frame*n,row*n,n,n,Math.round(run.x-s*meta.anchor.x),Math.round(run.y-s*meta.anchor.y),s,s);ctx.globalAlpha=1;}
function minimap(){const scale=2.3,ox=canvas.width-122,oy=19;rect(ox-9,oy-7,116,83,'#0c2023c0');for(let y=0;y<H;y++)for(let x=0;x<W;x++)if(map[y][x])rect(ox+x*scale,oy+y*scale,2,2,map[y][x]===2?'#61786b':'#35534b');for(let i=0;i<3;i++)if(!run.collected.includes(i))rect(ox+runes[i].x/TILE*scale-1,oy+runes[i].y/TILE*scale-1,3,3,'#8cdcd0');rect(ox+gate.x/TILE*scale-1,oy+gate.y/TILE*scale-1,3,3,'#ddbc7c');rect(ox+run.x/TILE*scale-1,oy+run.y/TILE*scale-1,3,3,'#f0f3cc')}
function render(t,dt){if(sheet&&!$('#intro').hidden){const pc=$('#hero-portrait').getContext('2d');pc.clearRect(0,0,256,256);pc.imageSmoothingEnabled=false;const n=meta.frameWidth;pc.drawImage(sheet,(Math.floor(t*12)%12)*n,9*n,n,n,0,0,256,256);}const box=canvas.getBoundingClientRect(),cw=box.width<620?400:800,ch=Math.round(cw*box.height/box.width);if(canvas.width!==cw||canvas.height!==ch){canvas.width=cw;canvas.height=ch}const tx=Math.max(0,Math.min(W*TILE-canvas.width,run.x-canvas.width/2)),ty=Math.max(0,Math.min(H*TILE-canvas.height,run.y-canvas.height*.61));cam.x+=(tx-cam.x)*Math.min(1,dt*8);cam.y+=(ty-cam.y)*Math.min(1,dt*8);rect(0,0,canvas.width,canvas.height,'#101f28');ctx.save();ctx.translate(-Math.round(cam.x),-Math.round(cam.y));
 for(let i=0;i<140;i++){const x=rand(i,8)*W*TILE,y=rand(i,9)*H*TILE;if(!map[Math.floor(y/TILE)]?.[Math.floor(x/TILE)])rect(x,y+Math.sin(t+i)*2,8+rand(i,4)*20,1,'#1a3540')}
 floor();
 for(const [x,y]of[[3,18],[10,18],[3,4],[14,4],[22,4],[36,4],[22,20],[37,20],[18,7]])torch(x*TILE+16,y*TILE,t);
 // Worn gold inlays guide the first steps out of the arrival chamber.
 for(let i=0;i<5;i++){const y=spawn.y-32-i*21;poly([[spawn.x,y-4],[spawn.x+3,y],[spawn.x,y+4],[spawn.x-3,y]],'#a89f67')}
 glow(spawn.x,spawn.y,72,'#57b8b626');ctx.strokeStyle='#68897a';ctx.beginPath();ctx.ellipse(spawn.x,spawn.y,36,13,0,0,Math.PI*2);ctx.stroke();
 for(let i=0;i<runes.length;i++)rune(runes[i],i,t);portal(t);
 for(const e of sentinels(run.time)){glow(e.x,e.y-12,45,'#b673c537');const bob=Math.sin(t*4+e.x)*3;poly([[e.x,e.y-26+bob],[e.x+12,e.y-12+bob],[e.x+7,e.y+1+bob],[e.x,e.y-4+bob],[e.x-7,e.y+1+bob],[e.x-12,e.y-12+bob]],'#967fac');rect(e.x-5,e.y-15+bob,3,4,'#efcabc');rect(e.x+3,e.y-15+bob,3,4,'#efcabc')}
 if(run.dash>0){trail.push({x:run.x,y:run.y,life:.3});}for(const p of trail){p.life-=dt;ctx.globalAlpha=Math.max(0,p.life)*.7;rect(p.x-12,p.y-12,24,12,'#c9eda8')}ctx.globalAlpha=1;trail=trail.filter(p=>p.life>0);
 const props=pillars.map(([x,y])=>({y:y*TILE+23,draw:()=>pillar(x,y)}));props.push({y:run.y,draw:hero});props.sort((a,b)=>a.y-b.y).forEach(p=>p.draw());
 for(const p of fx){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=24*dt;p.life-=dt;ctx.globalAlpha=clamp(p.life/.5);rect(p.x,p.y,3,3,p.color)}ctx.globalAlpha=1;fx=fx.filter(p=>p.life>0);
 for(let i=0;i<45;i++){const X=rand(i,5)*W*TILE+Math.sin(t*.3+i)*12,Y=rand(i,3)*H*TILE+Math.cos(t*.4+i)*7;if(map[Math.floor(Y/TILE)]?.[Math.floor(X/TILE)]){ctx.globalAlpha=.25+.4*Math.max(0,Math.sin(t+i));rect(X,Y,2,2,'#b8d68b')}}ctx.globalAlpha=1;ctx.restore();
 const v=ctx.createRadialGradient(canvas.width/2,canvas.height*.5,100,canvas.width/2,canvas.height*.5,canvas.width*.75);v.addColorStop(0,'transparent');v.addColorStop(1,'#050e1685');ctx.fillStyle=v;ctx.fillRect(0,0,canvas.width,canvas.height);minimap();}
const clamp=v=>Math.min(1,Math.max(0,v));let hudTime=0;
function tick(now){const dt=Math.min(.04,(now-last)/1000||.016);last=now;clock+=dt;if(!paused){const events=step(run,dt,{x:(keys.has('d')||keys.has('ArrowRight'.toLowerCase())?1:0)-(keys.has('a')||keys.has('ArrowLeft'.toLowerCase())?1:0),y:(keys.has('s')||keys.has('ArrowDown'.toLowerCase())?1:0)-(keys.has('w')||keys.has('ArrowUp'.toLowerCase())?1:0)});for(const e of events){if(e.type==='rune'){burst(e.x,e.y,'#b4edb9',36);chime([440,554.37,659.25]);speak(run.collected.length===3?'Alle Runen gefunden. Die Tür im Südosten ist erwacht.':`Runensplitter ${run.collected.length} / 3 · Das Portal erinnert sich.`)}if(e.type==='hit'){burst(e.x,e.y,'#d3a9c6',18);speak('Ein Irrlicht! Nutze Dash zum Ausweichen. Deine Runen bleiben erhalten.');chime([164.81,130.81])}if(e.type==='won'){$('#ending').hidden=false;$('#result').textContent=`${gameName} hat die erste Tür in ${Math.round(run.time)} Sekunden geöffnet. Drei Runen, ein neues Zuhause. Deine Figur ist bereit für ein größeres Abenteuer.`;chime([293.66,369.99,440,587.33]);burst(run.x,run.y,'#e4efb6',60);$('#again').focus();}}
 }render(clock,paused?0:dt);hudTime+=dt;if(hudTime>.15){hud();hudTime=0}requestAnimationFrame(tick)}
cam.x=Math.max(0,spawn.x-480);cam.y=Math.max(0,spawn.y-350);hud();requestAnimationFrame(tick);

$('#character-name').addEventListener('input',e=>$('#portrait-name').textContent=e.target.value.trim()||gameName);
