import {TILE,W,H,map,pillars,spawn,sites,classes,motives,createJourney,pathTo,step,dash,sentinels,ability,choose,target,objective,serialize,restore} from './heimkehr-core.js';
const $=s=>document.querySelector(s),canvas=$('#dungeon'),ctx=canvas.getContext('2d'),keys=new Set();
let run=createJourney(),sheet=null,meta=null,cam={x:0,y:0},last=0,fx=[],toastTimer=0,paused=false,gameName='Reisender',soundCtx,clock=0,saveKey='',accepted=false,saveClock=0,visualAttacks=[],lumiPos={...spawn},journalWasPaused=false,restored=false,started=false;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const entryText={beacon:'Du hast die Lichtquelle geweckt. Aus einem Flüstern wurde eine Stimme.',lumi:'Du hast Lumi aus dem Siegel befreit. Du reist jetzt nicht mehr allein.',core:'Lumi hat die Maschine erkannt. Gemeinsam habt ihr den letzten Energiekern geborgen.',secret:'Im Licht erschien eine alte Inschrift: „Ein Zuhause ist ein Licht, das jemand für dich anlässt.“',garden:'Du hast den Lichtgarten gepflanzt. Neues Leben schenkt deinem Licht neue Kraft.',guardian:'Du hast den alten Wächter geweckt. Selbst die Irrlichter finden hier Frieden.'};
function say(text,speaker='LUMI'){ $('#speaker').textContent=speaker;$('#dialogue').textContent='„'+text+'“';}
function save(){if(!saveKey||!started)return;run.name=gameName;try{localStorage.setItem(saveKey,serialize(run));$('#save-status').textContent='Reise auf diesem Gerät gespeichert.'}catch{$('#save-status').textContent='Speichern nicht möglich — diese Reise bleibt nur bis zum Schließen.'}}
function blocked(){return paused||!$('#intro').hidden||!$('#choice-panel').hidden||!$('#ending').hidden||!$('#journal-panel').hidden}
function hud(){const c=classes[run.role],n=Number(run.beacon)+Number(run.rescued)+Number(run.core);$('#hero-name').textContent=gameName;$('#hero-detail').textContent=c.name+(run.rescued?' · Lumi an deiner Seite':' · Mit deiner Laterne');$('#progress').replaceChildren(document.createTextNode('◆ '.repeat(n)+'○ '.repeat(3-n)));const small=document.createElement('small');small.textContent=run.choice?'Zuhause angekommen':['Das Erwachen','Eine Stimme im Licht','Der letzte Kern','Die Heimkehr'][n];$('#progress').append(small);$('#journal-count').textContent=run.journal.length;$('#chapter').textContent=run.choice?'DEIN ZUHAUSE':['01 / DIE LICHTQUELLE','02 / DIE GEFANGENE STIMME','03 / DER LETZTE KERN','04 / WAS BLEIBT'][n];$('#objective').textContent=objective(run);const t=sites[target(run)],near=Math.hypot(t.x-run.x,t.y-run.y)<78;$('#ability').disabled=blocked()||run.phase!=='explore'||run.abilityCooldown>0;$('#ability').replaceChildren(document.createTextNode(run.abilityCooldown>0?run.abilityCooldown.toFixed(1)+' s':near&&!run.core?'✦ '+(run.beacon?run.rescued?'Kern bergen':'Lumi befreien':'Lichtquelle wecken'):c.skill));const hint=document.createElement('small');hint.textContent='E · '+(near&&!run.core?'Licht bündeln':'Irrlichter vertreiben');$('#ability').append(hint);$('#dash').disabled=blocked()||run.phase!=='explore'||run.cooldown>0;$('#dash').innerHTML=run.cooldown>0?`✦ ${run.cooldown.toFixed(1)} s<small>lädt auf</small>`:'✦ Dash <small>Leertaste</small>';$('#guide').disabled=blocked()||run.phase!=='explore';$('#guide').textContent=run.choice?'Zum Zuhause →':'Zum Ziel →';canvas.setAttribute('aria-label',`Heimkehr: ${gameName}, ${c.name}. ${objective(run)} Position ${Math.round(run.x)}, ${Math.round(run.y)}. Erinnerungen ${run.journal.length}. Klicken zum Laufen. E für Fähigkeit. Leertaste für Dash.`);}
async function accept(data){if(accepted||!data||data.type!=='form-pixel-adventure'||typeof data.sheet!=='string'||!data.sheet.startsWith('data:image/png;')||data.sheet.length>20e6)return;accepted=true;try{const im=new Image();im.src=data.sheet;await im.decode();const m=data.metadata;if(!m||![48,64,96].includes(m.frameWidth)||im.width!==m.frameWidth*12||im.height!==m.frameWidth*24)throw Error('Sprite-Paket ungültig');sheet=im;meta=m;saveKey='form-pixel-heimkehr-v1:'+encodeURIComponent(m.source||data.name||'figure');let saved=null;try{saved=localStorage.getItem(saveKey)}catch{}if(saved){run=restore(saved);restored=run.journal.length>0||run.time>0;}gameName=restored?run.name:(data.name||m.source||'Reisender').split(' / ')[0].slice(0,24);$('#character-name').value=gameName;$('#portrait-name').textContent=gameName;$('#motive').value=run.motive;$(`input[name=class][value=${run.role}]`).checked=true;$('#credits').textContent=data.credit||'Eigene Figur';$('#begin').disabled=false;if(restored){$('#begin').textContent='Meine Reise fortsetzen →';$('#save-hint').textContent=run.choice?'Dein Zuhause und Lumi warten auf dich.':'Gespeicherter Fortschritt gefunden. Deine Klasse kannst du neu wählen.';}lumiPos={x:run.x-35,y:run.y};hud()}catch(e){accepted=false;speak(e.message)}}
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent)return;if(e.data?.type==='adventure-close'){save();paused=true;keys.clear()}else accept(e.data)});
try{const data=JSON.parse(sessionStorage.getItem('form-pixel-adventure')||'null');if(data)accept(data);else $('#save-hint').textContent='Wähle zuerst deine Figur in der Werkstatt.'}catch{}
function back(){save();keys.clear();paused=true;if(parent!==window)parent.postMessage({type:'adventure-exit'},location.origin);else location.href='./'}
$('#close').onclick=back;$('#finish').onclick=back;
$('#begin').onclick=()=>{if(!sheet)return;gameName=$('#character-name').value.trim()||gameName;run.name=gameName;run.role=$('input[name=class]:checked').value;run.motive=$('#motive').value;run.phase='explore';started=true;paused=false;$('#intro').hidden=true;canvas.focus();burst(run.x,run.y,classes[run.role].color,35);chime([293.66,440,587.33]);say(run.choice?'Du bist wieder da. Ich habe das Licht für dich angelassen.':run.rescued?'Ich bin noch hier. Lass uns unsere Reise zu Ende bringen.':run.motive==='home'?'Vielleicht ist dies der Ort, den du suchst. Folge meinem Licht.':run.motive==='light'?'Du willst Licht zurückbringen? Im Norden schläft noch ein Funke.':'Du suchst Antworten? Wecke die alte Lichtquelle im Norden.',run.rescued?'LUMI':'DEINE LATERNE');save();hud()};
function pause(value){if(run.phase!=='explore'||!$('#choice-panel').hidden||!$('#ending').hidden||!$('#journal-panel').hidden)return;paused=value;keys.clear();$('#pause-panel').hidden=!value;$('#pause').textContent=value?'▶':'Ⅱ';save();if(!value)canvas.focus();hud()}
$('#pause').onclick=()=>pause(!paused);$('#resume').onclick=()=>pause(false);window.addEventListener('blur',()=>{keys.clear();pause(true)});document.addEventListener('visibilitychange',()=>{if(document.hidden){save();pause(true)}});window.addEventListener('pagehide',save);
function doDash(){if(blocked())return;if(dash(run)){burst(run.x,run.y,'#c9e5ba',12);chime([220,440])}canvas.focus()}
function doAbility(){if(blocked())return;handle(ability(run));canvas.focus();hud()}
$('#dash').onclick=doDash;$('#ability').onclick=doAbility;
window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA','BUTTON','SUMMARY'].includes(e.target.tagName))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d','W','A','S','D',' ','e','E'].includes(e.key)){e.preventDefault();if(e.key===' '){if(!e.repeat)doDash()}else if(e.key.toLowerCase()==='e'){if(!e.repeat)doAbility()}else if(!blocked())keys.add(e.key.toLowerCase())}if(e.key==='Escape')pause(!paused)});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
for(const b of document.querySelectorAll('[data-dir]')){const key={up:'w',left:'a',down:'s',right:'d'}[b.dataset.dir];let downAt=0;b.onclick=()=>{if(run.phase!=='explore'||blocked())return;if(performance.now()-downAt<220||downAt===0){const [dx,dy]={w:[0,-32],a:[-32,0],s:[0,32],d:[32,0]}[key];run.path=pathTo(run,{x:run.x+dx,y:run.y+dy})}};b.onpointerdown=e=>{if(blocked())return;downAt=performance.now();e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(key)};for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,()=>keys.delete(key))}
$('#guide').onclick=()=>{if(blocked())return;const dest=sites[target(run)];run.path=pathTo(run,dest);if(run.path.length)speak('Du läufst zum markierten Ziel. WASD oder ein Bodenklick ändern den Weg.');canvas.focus()};
canvas.addEventListener('pointerdown',e=>{if(run.phase!=='explore'||blocked())return;const b=canvas.getBoundingClientRect(),mx=(e.clientX-b.left)*canvas.width/b.width,my=(e.clientY-b.top)*canvas.height/b.height;const onMap=mx>canvas.width-131&&my<102;const dest=onMap?{x:(mx-(canvas.width-122))/2.3*TILE,y:(my-19)/2.3*TILE}:{x:mx+cam.x,y:my+cam.y};const route=pathTo(run,dest);if(route.length){run.path=route;burst(dest.x,dest.y,'#d7c998',8)}else speak('Wähle einen Punkt auf dem Steinboden.');canvas.focus()});
function journal(){refreshArchives();journalWasPaused=paused;keys.clear();$('#journal-identity').textContent=gameName+' · '+classes[run.role].name+' · '+motives[run.motive];$('#journal-entries').replaceChildren();for(const id of run.journal){const li=document.createElement('li');li.textContent=entryText[id];$('#journal-entries').append(li)}if(!run.journal.length){const li=document.createElement('li');li.textContent='Deine erste Seite ist noch leer. Im Norden wartet ein Licht.';$('#journal-entries').append(li)}$('#journal-panel').hidden=false;$('#pause-panel').hidden=true;$('#journal-close').focus();hud()}
$('#journal-button').onclick=()=>{if(!$('#intro').hidden||!$('#choice-panel').hidden||!$('#ending').hidden)return;journal()};$('#journal-close').onclick=()=>{$('#journal-panel').hidden=true;paused=journalWasPaused;$('#pause-panel').hidden=!paused;canvas.focus();hud()};
$('#restart').onclick=()=>{try{localStorage.setItem(saveKey+':archive:'+Date.now(),serialize(run))}catch{speak('Archivieren nicht möglich. Deine bisherige Reise bleibt erhalten.');return}run=createJourney();started=false;restored=false;paused=false;keys.clear();fx=[];visualAttacks=[];$('#journal-panel').hidden=true;$('#pause-panel').hidden=true;$('#intro').hidden=false;$('#begin').textContent='Neue Reise beginnen →';$('#save-hint').textContent='Die vorherige Reise ist lokal archiviert.';$('#character-name').value=gameName;$('#character-name').focus();hud()};
for(const choice of ['garden','guardian'])$('#choose-'+choice).onclick=()=>{if(!choose(run,choice))return;$('#choice-panel').hidden=true;$('#ending-title').innerHTML=choice==='garden'?'Hier wächst<br>ein Anfang.':'Hier darfst du<br>bleiben.';const personal=run.motive==='home'?'Du hast einen Ort gefunden, der auf dich wartet.':run.motive==='light'?'Das Licht, das du gesucht hast, leuchtet jetzt für andere.':'Die Ruine hat dir eine Antwort gegeben: Dieser Ort brauchte jemanden, der bleibt.';$('#result').textContent=(choice==='garden'?'Lumi hat im Lichtgarten ein Zuhause gefunden. Deine Fähigkeit lädt jetzt doppelt so schnell. ':'Der Wächter steht wieder. Die Irrlichter sind friedlich geworden. ')+personal;$('#ending').hidden=false;burst(spawn.x,spawn.y,choice==='garden'?'#dce9a0':'#b9e4e9',70);chime([293.66,369.99,440,587.33]);say(choice==='garden'?'Du hast mir einen Garten geschenkt. Ich glaube, ich bleibe.':'Er kennt meinen Namen noch. Danke, dass du ihn geweckt hast.');save();$('#continue').focus();hud()};
$('#continue').onclick=()=>{$('#ending').hidden=true;canvas.focus();hud()};
function handle(events){for(const e of events){if(e.type==='ability'){const a=run.direction*Math.PI/4;visualAttacks.push({...e,life:.38,to:e.to||{x:e.x+Math.sin(a)*classes[run.role].range,y:e.y+Math.cos(a)*classes[run.role].range}});burst(run.x,run.y-20,classes[run.role].color,run.role==='mage'?32:12);chime(run.role==='sword'?[220,330]:run.role==='mage'?[440,659,880]:[660,990]);}
 if(e.type==='disperse'){burst(e.x,e.y,'#ccbce3',25);speak('Das Irrlicht löst sich für einen Moment auf.');}
 if(e.type==='beacon'){say('Du kannst mich hören! Ich bin Lumi. Das Siegel im Osten hält mich fest.');burst(sites.beacon.x,sites.beacon.y,'#f5d897',55);chime([330,440,660]);}
 if(e.type==='rescue'){say('Endlich frei. Die alte Maschine im Süden hat noch einen Kern. Komm, zusammen schaffen wir das!');lumiPos={...sites.lumi};burst(sites.lumi.x,sites.lumi.y,'#ffdf8b',50);chime([440,550,880]);}
 if(e.type==='core'){say('Ein einziger Kern. Er könnte den Garten nähren oder unseren Wächter wecken. Lass uns nach Hause gehen.');burst(sites.core.x,sites.core.y,'#f3d28a',50);}
 if(e.type==='secret'){say('Jemand hat diese Worte für uns hinterlassen. Ich bewahre sie in deinem Buch auf.');speak('Verborgene Erinnerung entdeckt · im Buch gespeichert');}
 if(e.type==='hit'){burst(e.x,e.y,'#cba0c6',15);speak('Irrlicht! Nutze deine Fähigkeit oder Dash. Du verlierst nichts.');}
 if(e.type==='choose'){keys.clear();$('#choice-panel').hidden=false;$('#choose-garden').focus()}
 if(e.type!=='ability'&&e.type!=='hit'&&e.type!=='disperse')save();}}
$('#character-name').addEventListener('input',e=>$('#portrait-name').textContent=e.target.value.trim()||gameName);
for(const radio of document.querySelectorAll('[name=class]'))radio.onchange=()=>{run.role=radio.value;hud()};
const rand=(x,y)=>{const n=Math.sin(x*127.1+y*311.7)*43758.5453;return n-Math.floor(n)};
const rect=(x,y,w,h,c)=>{ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),w,h)};
function poly(points,c){ctx.fillStyle=c;ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.fill()}
function glow(x,y,r,c){const g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,c);g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.fillRect(x-r,y-r,r*2,r*2)}
function speak(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3500)}
function chime(notes){if(!$('#sound').checked)return;try{soundCtx??=new AudioContext();soundCtx.resume();notes.forEach((hz,i)=>{const o=soundCtx.createOscillator(),g=soundCtx.createGain(),t=soundCtx.currentTime+i*.09;o.type='sine';o.frequency.value=hz;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.065,t+.012);g.gain.exponentialRampToValueAtTime(.001,t+.42);o.connect(g).connect(soundCtx.destination);o.start(t);o.stop(t+.44)})}catch{}}
function burst(x,y,color,count=22){for(let i=0;i<count;i++){const a=i/count*Math.PI*2;fx.push({x,y,vx:Math.cos(a)*(25+i%6*9),vy:Math.sin(a)*(25+i%5*9)-20,life:.7+i%4*.15,max:1.2,color})}}

function floor(){for(let y=0;y<H;y++)for(let x=0;x<W;x++){if(!map[y][x])continue;const X=x*TILE,Y=y*TILE,n=rand(x,y);rect(X,Y,32,32,'#203332');rect(X+1,Y+1,30,29,n>.65?'#344844':n>.3?'#30433f':'#293e3b');rect(X+2,Y+2,28,1,'#46574b');if(n>.62)rect(X+7,Y+19,10,1,'#50604d');if(n<.2){rect(X+23,Y+5,1,10,'#1e3332');rect(X+19,Y+15,5,1,'#1e3332')}if(n>.87){rect(X+3,Y+6,5,3,'#4d6248');rect(X+5,Y+4,2,4,'#627249')}
 if(y===0||!map[y-1][x]){rect(X,Y-28,32,26,'#203135');rect(X+1,Y-31,30,7,'#597067');rect(X+2,Y-23,28,4,'#3e544f');rect(X+3,Y-7,26,2,'#192b2d');if(x%4===0){rect(X+10,Y-22,13,17,'#15272a');rect(X+13,Y-20,7,12,'#2a4140')}}
 if(!map[y+1]?.[x]){rect(X,Y+31,32,12,'#14282c');rect(X,Y+32,32,2,'#48584b')}
 if(!map[y]?.[x-1])rect(X-5,Y,5,32,'#14282b');if(!map[y]?.[x+1])rect(X+32,Y,5,32,'#14282b');}}
function pillar(x,y){const X=x*TILE+16,Y=y*TILE+23;ctx.fillStyle='#07151880';ctx.beginPath();ctx.ellipse(X+17,Y+6,27,11,0,0,Math.PI*2);ctx.fill();rect(X-16,Y-5,32,10,'#556660');rect(X-13,Y-49,26,46,'#4b605a');rect(X+3,Y-49,10,46,'#2f4946');rect(X-10,Y-47,4,39,'#79907b');rect(X-17,Y-55,34,9,'#778c76');rect(X-14,Y-58,28,4,'#a0ac88');rect(X-9,Y-28,17,3,'#263f3c');rect(X-11,Y-20,6,11,'#526d45');}
function torch(x,y,t){glow(x,y-20,80,'#e3a55424');rect(x-3,y-17,6,17,'#745b40');rect(x-5,y-18,10,4,'#b18b50');const k=Math.sin(t*12+x)*3;poly([[x-6,y-21],[x-3,y-35+k],[x,y-28],[x+4,y-40-k],[x+7,y-22]],'#e59753');poly([[x-3,y-21],[x,y-32],[x+4,y-20]],'#f4dc93');}

function hero(){if(!sheet||!meta)return;glow(run.x,run.y-22,56,'#b6d78a16');const n=meta.frameWidth,frame=Math.floor(run.time*12)%12,row=(run.moving?2:1)*8+run.direction,s=128;ctx.fillStyle='#03121790';ctx.beginPath();ctx.ellipse(run.x,run.y,22,8,0,0,Math.PI*2);ctx.fill();if(run.invulnerable>0&&Math.floor(clock*12)%2===0)ctx.globalAlpha=.45;ctx.imageSmoothingEnabled=false;ctx.drawImage(sheet,frame*n,row*n,n,n,Math.round(run.x-s*meta.anchor.x),Math.round(run.y-s*meta.anchor.y),s,s);ctx.globalAlpha=1;}

function label(text,x,y,color='#d9d3aa'){ctx.font='9px Consolas,monospace';ctx.textAlign='center';ctx.fillStyle='#0b1b22';ctx.fillRect(x-ctx.measureText(text).width/2-5,y-10,ctx.measureText(text).width+10,14);ctx.fillStyle=color;ctx.fillText(text,x,y);}
function crystal(x,y,t,color='#ecce83',size=1){const b=reduced?0:Math.sin(t*2)*3;glow(x,y-10,55,color+'35');poly([[x,y-30*size+b],[x+10*size,y-15*size+b],[x,y+b],[x-10*size,y-15*size+b]],color);poly([[x,y-30*size+b],[x,y+b],[x-10*size,y-15*size+b]],'#fbf0bc');}
function friend(x,y,t,freed=true){const b=reduced?0:Math.sin(t*3)*3;glow(x,y-22,freed?75:40,'#fbe0a640');rect(x-11,y-29+b,22,19,'#d99f57');rect(x-8,y-34+b,16,26,'#f3d489');rect(x-6,y-29+b,12,15,'#fff1b5');rect(x-4,y-24+b,2,3,'#3d4c3c');rect(x+3,y-24+b,2,3,'#3d4c3c');rect(x-14,y-15+b,5,3,'#dbad64');rect(x+9,y-15+b,5,3,'#dbad64');if(!freed){ctx.strokeStyle='#aa8fc3';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(x,y-17,23,34,0,0,Math.PI*2);ctx.stroke();for(let i=0;i<3;i++)rect(x-19+i*17,y-18,4,5,'#d3b7e9')}}
function home(t){const {x,y}=spawn;glow(x,y-5,run.choice?180:70,run.choice==='garden'?'#b9d28424':run.choice==='guardian'?'#9dccdc27':'#d9bc8920');ctx.strokeStyle=run.choice?'#d1c18c':'#807959';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(x,y,39,16,0,0,Math.PI*2);ctx.stroke();
 for(const sign of [-1,1]){const X=x+sign*80,Y=y-35;rect(X-29,Y-8,58,21,'#253e38');rect(X-31,Y-9,62,5,'#7b8160');rect(X-25,Y-5,50,12,'#182d29');if(run.choice==='garden')for(let j=0;j<7;j++){const xx=X-22+j*7,yy=Y-12-(j%3)*5;rect(xx,yy,2,16,'#7e9a58');rect(xx-4,yy+4,6,3,'#adc283');rect(xx-3,yy-4,8,7,j%2?'#eab98d':'#e9dc9e');rect(xx,yy-1,2,2,'#fff4c5');glow(xx,yy,18,'#e2d69218')}}
 const X=x,Y=y-96;rect(X-23,Y+3,46,9,'#536a60');rect(X-16,Y-33,32,37,run.choice==='guardian'?'#8a9b85':'#3e514d');rect(X-24,Y-24,12,28,'#455f57');rect(X+12,Y-24,12,28,'#455f57');rect(X-13,Y-53,26,21,run.choice==='guardian'?'#b9c8a0':'#647263');rect(X-8,Y-45,5,4,run.choice==='guardian'?'#fbecae':'#263933');rect(X+3,Y-45,5,4,run.choice==='guardian'?'#fbecae':'#263933');if(run.choice==='guardian'){crystal(X,Y-14,t,'#a6dfd8',.45);glow(X,Y-30,90,'#a9d8b422')}label(run.choice==='garden'?'DEIN LICHTGARTEN':run.choice==='guardian'?'DER WÄCHTER WACHT':'DER VERLASSENE ZUFLUCHTSORT',x,y+46);}
function relics(t){const b=sites.beacon;rect(b.x-18,b.y-2,36,10,'#708477');rect(b.x-11,b.y-19,22,20,'#526d63');crystal(b.x,b.y-17,t,run.beacon?'#f1d98e':'#819c96');label(run.beacon?'LICHTQUELLE ERWACHT':'DIE LICHTQUELLE',b.x,b.y+27);if(!run.rescued){friend(sites.lumi.x,sites.lumi.y,t,false);label(run.beacon?'LUMIS SIEGEL':'EIN FLÜSTERN',sites.lumi.x,sites.lumi.y+28)}const c=sites.core;for(let i=0;i<3;i++){rect(c.x-28+i*24,c.y-20-(i%2)*20,10,36,'#7a8971');rect(c.x-30+i*24,c.y-24-(i%2)*20,14,5,'#b1a77b')}ctx.strokeStyle='#858967';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(c.x,c.y+3,38,17,0,0,Math.PI*2);ctx.stroke();if(!run.core)crystal(c.x,c.y-15,t,'#eccd87',1.2);label(run.core?'DIE MASCHINE RUHT':'DER LETZTE KERN',c.x,c.y+35);const z=sites.secret;rect(z.x-18,z.y-17,36,20,'#5c7162');for(let i=0;i<4;i++)rect(z.x-12+i*7,z.y-12,3,8,run.secret?'#ebd993':'#819785');if(run.secret)glow(z.x,z.y,50,'#e5d79d30');else if(Math.hypot(run.x-z.x,run.y-z.y)<130)label('DIE WAND FLÜSTERT …',z.x,z.y+20);}
function minimap(){const scale=2.3,ox=canvas.width-122,oy=19;rect(ox-9,oy-7,116,83,'#0c2023e8');for(let y=0;y<H;y++)for(let x=0;x<W;x++)if(map[y][x])rect(ox+x*scale,oy+y*scale,2,2,map[y][x]===2?'#61786b':'#35534b');for(const [id,p]of Object.entries(sites)){if(id==='secret')continue;rect(ox+p.x/TILE*scale-1,oy+p.y/TILE*scale-1,3,3,id===target(run)?'#ffe5a0':'#799587')}const p=sites[target(run)];ctx.strokeStyle='#ddc780';ctx.strokeRect(ox+p.x/TILE*scale-4,oy+p.y/TILE*scale-4,8,8);rect(ox+run.x/TILE*scale-1,oy+run.y/TILE*scale-1,3,3,'#f8ffe4')}
function render(t,dt){if(sheet&&!$('#intro').hidden){const pc=$('#hero-portrait').getContext('2d');pc.clearRect(0,0,256,256);pc.imageSmoothingEnabled=false;const n=meta.frameWidth;pc.drawImage(sheet,(reduced?0:Math.floor(t*12)%12)*n,9*n,n,n,0,0,256,256)}const box=canvas.getBoundingClientRect(),cw=box.width<620?400:800,ch=Math.max(180,Math.round(cw*box.height/Math.max(1,box.width)));if(canvas.width!==cw||canvas.height!==ch){canvas.width=cw;canvas.height=ch}const tx=Math.max(0,Math.min(W*TILE-canvas.width,run.x-canvas.width/2)),ty=Math.max(0,Math.min(H*TILE-canvas.height,run.y-canvas.height*.62));cam.x+=(tx-cam.x)*Math.min(1,dt*9);cam.y+=(ty-cam.y)*Math.min(1,dt*9);rect(0,0,canvas.width,canvas.height,'#101e27');ctx.save();ctx.translate(-Math.round(cam.x),-Math.round(cam.y));
 for(let i=0;i<100;i++){const x=rand(i,8)*W*TILE,y=rand(i,9)*H*TILE;if(!map[Math.floor(y/TILE)]?.[Math.floor(x/TILE)])rect(x,y+(reduced?0:Math.sin(t+i)*2),8+rand(i,4)*20,1,'#1a3540')}
 floor();for(const [x,y]of[[3,18],[10,18],[3,4],[14,4],[22,4],[36,4],[22,20],[37,20],[18,7]])torch(x*TILE+16,y*TILE,reduced?0:t);home(t);relics(t);
 const dest=sites[target(run)];if(!run.choice){const r=35+(reduced?0:Math.sin(t*3)*3);ctx.strokeStyle='#e5c485';ctx.lineWidth=1;ctx.beginPath();ctx.ellipse(dest.x,dest.y+7,r,r*.35,0,0,Math.PI*2);ctx.stroke();}
 for(const [i,e]of sentinels(run.time).entries()){if(run.dispersed[i]>0)continue;const peaceful=run.choice==='guardian';glow(e.x,e.y-12,45,peaceful?'#96cda637':'#b673c537');const bob=reduced?0:Math.sin(t*4+e.x)*3;poly([[e.x,e.y-26+bob],[e.x+12,e.y-12+bob],[e.x+7,e.y+1+bob],[e.x,e.y-4+bob],[e.x-7,e.y+1+bob],[e.x-12,e.y-12+bob]],peaceful?'#a6c4a2':'#967fac');rect(e.x-5,e.y-15+bob,3,4,'#efdfbc');rect(e.x+3,e.y-15+bob,3,4,'#efdfbc')}
 if(run.rescued){lumiPos.x+=((run.x-36)-lumiPos.x)*Math.min(1,dt*4);lumiPos.y+=((run.y-8)-lumiPos.y)*Math.min(1,dt*4)}
 const props=pillars.map(([x,y])=>({y:y*TILE+23,draw:()=>pillar(x,y)}));props.push({y:run.y,draw:hero});if(run.rescued)props.push({y:lumiPos.y,draw:()=>friend(lumiPos.x,lumiPos.y,t)});props.sort((a,b)=>a.y-b.y).forEach(p=>p.draw());
 if(!run.rescued){glow(run.x-27,run.y-37,30,'#e9d59830');rect(run.x-29,run.y-40,5,7,'#ecd697')}
 for(const a of visualAttacks){a.life-=dt;ctx.globalAlpha=Math.max(0,a.life/.38);ctx.strokeStyle=classes[a.role].color;ctx.lineWidth=a.role==='sword'?5:2;ctx.beginPath();if(a.role==='bow'){const f=1-a.life/.38;ctx.moveTo(a.x+(a.to.x-a.x)*Math.max(0,f-.3),a.y-20+(a.to.y-a.y)*Math.max(0,f-.3));ctx.lineTo(a.x+(a.to.x-a.x)*f,a.y-20+(a.to.y-a.y)*f)}else if(a.role==='mage')ctx.arc(a.x,a.y-15,20+(1-a.life/.38)*135,0,Math.PI*2);else{const angle=Math.PI/2-run.direction*Math.PI/4;ctx.arc(a.x,a.y-18,60,angle-1.4,angle+1.4)}ctx.stroke()}ctx.globalAlpha=1;visualAttacks=visualAttacks.filter(a=>a.life>0);
 for(const p of fx){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=24*dt;p.life-=dt;ctx.globalAlpha=Math.max(0,Math.min(1,p.life/.5));rect(p.x,p.y,3,3,p.color)}ctx.globalAlpha=1;fx=fx.filter(p=>p.life>0);if(!reduced)for(let i=0;i<40;i++){const x=rand(i,5)*W*TILE+Math.sin(t*.3+i)*12,y=rand(i,3)*H*TILE+Math.cos(t*.4+i)*7;if(map[Math.floor(y/TILE)]?.[Math.floor(x/TILE)]){ctx.globalAlpha=.25+.4*Math.max(0,Math.sin(t+i));rect(x,y,2,2,'#c7d393')}}ctx.globalAlpha=1;ctx.restore();const v=ctx.createRadialGradient(canvas.width/2,canvas.height*.5,80,canvas.width/2,canvas.height*.5,canvas.width*.7);v.addColorStop(0,'transparent');v.addColorStop(1,'#050e1660');ctx.fillStyle=v;ctx.fillRect(0,0,canvas.width,canvas.height);minimap();}
let hudTime=0;function tick(now){const dt=Math.min(.04,(now-last)/1000||.016);last=now;clock+=dt;if(!blocked()){handle(step(run,dt,{x:(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),y:(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0)}));saveClock+=dt;if(saveClock>2){save();saveClock=0}}render(clock,paused?0:dt);hudTime+=dt;if(hudTime>.12){hud();hudTime=0}requestAnimationFrame(tick)}cam.x=0;cam.y=450;hud();requestAnimationFrame(tick);

// Keep keyboard focus inside story dialogs while they are open.
window.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const panel=['#choice-panel','#ending','#journal-panel'].map($).find(el=>!el.hidden);if(!panel)return;const controls=[...panel.querySelectorAll('button,input,select,summary')].filter(el=>!el.disabled&&el.getClientRects().length);if(!controls.length)return;const first=controls[0],last=controls.at(-1);if(e.shiftKey&&(document.activeElement===first||!panel.contains(document.activeElement))){e.preventDefault();last.focus()}else if(!e.shiftKey&&(document.activeElement===last||!panel.contains(document.activeElement))){e.preventDefault();first.focus()}});

function refreshArchives(){const select=$('#archives');select.replaceChildren();const empty=document.createElement('option');empty.value='';empty.textContent='Reise auswählen …';select.append(empty);try{const keys=Object.keys(localStorage).filter(k=>k.startsWith(saveKey+':archive:')).sort().reverse();for(const key of keys){const s=restore(localStorage.getItem(key));const option=document.createElement('option');option.value=key;option.textContent=s.name+' · '+classes[s.role].name+' · '+(s.choice==='garden'?'Lichtgarten':s.choice==='guardian'?'Wächter':s.journal.length+' Erinnerungen');select.append(option)}}catch{}$('#restore-archive').disabled=true;}
$('#archives').onchange=()=>$('#restore-archive').disabled=!$('#archives').value;
$('#restore-archive').onclick=()=>{const key=$('#archives').value;if(!key.startsWith(saveKey+':archive:'))return;try{const raw=localStorage.getItem(key);if(!raw)return;localStorage.setItem(saveKey+':archive:'+Date.now(),serialize(run));run=restore(raw);gameName=run.name;run.phase='explore';started=true;paused=false;keys.clear();fx=[];visualAttacks=[];lumiPos={x:run.x-35,y:run.y};$('#journal-panel').hidden=true;$('#pause-panel').hidden=true;save();say('Da bist du wieder. Unsere Geschichte ist noch hier.');canvas.focus();hud()}catch{speak('Diese Reise konnte nicht geladen werden.')}};
$('#next-chapter').onclick=()=>{save();location.href='./ruins.html'};
