import {createRun,classes,spawn,markers,nextTarget,objective,pathTo,beginCharge,releaseCharge,attack,dash,step,drain,retry,serialize,restore} from './ruins-core.js';
import {createArt} from './ruins-art.js';
const $=s=>document.querySelector(s),canvas=$('#scene'),art=createArt(canvas),keys=new Set(),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let run=createRun(),assets={hero:null,props:[],weapon:null},fx=[],saveKey='',paused=false,accepted=false,started=false,last=0,clock=0,shake=0,hitstop=0,hudTimer=0,saveTimer=0,soundCtx,toastTimer,bannerTimer,priorPause=false;
const classHelp={sword:'E: schneller Schwung. Ein exakt getimter Dash pariert und verstärkt deinen nächsten Treffer.',mage:'E: Stoßwelle. Drücke Gegner gegen Mauern: Das betäubt sie und verursacht zusätzlichen Schaden.',bow:'E oder Angriff halten und lösen. Ab 0,7 Sekunden trifft dein Pfeil stärker und durchdringt zwei Ziele.'};
const roomNames=['DER ZUFLUCHTSORT','I · DIE DORNENHALLE','II · DER SPIEGELGARTEN','III · DAS VERWURZELTE HERZ','DIE VERBORGENE GÄRTNERIN'];
function blocked(){return paused||run.phase!=='play'||['#intro','#down','#ending','#journal','#pause-panel'].some(id=>!$(id).hidden)}
function speak(s){$('#toast').textContent=s;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2700)}
function say(s){$('#dialogue').textContent='„'+s+'“'}
function banner(s){$('#room-banner').textContent=s;$('#room-banner').classList.add('visible');clearTimeout(bannerTimer);bannerTimer=setTimeout(()=>$('#room-banner').classList.remove('visible'),2100)}
function sound(hz=440,kind='sine',duration=.13){if(!$('#sound').checked)return;try{soundCtx??=new AudioContext();soundCtx.resume();const t=soundCtx.currentTime,o=soundCtx.createOscillator(),g=soundCtx.createGain();o.type=kind;o.frequency.setValueAtTime(hz,t);o.frequency.exponentialRampToValueAtTime(Math.max(50,hz*.6),t+duration);g.gain.setValueAtTime(.05,t);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g).connect(soundCtx.destination);o.start(t);o.stop(t+duration)}catch{}}
function burst(x,y,color,count=20){for(let i=0;i<count;i++){const a=i/count*Math.PI*2,v=30+i%5*15;fx.push({x,y:y-15,vx:Math.cos(a)*v,vy:Math.sin(a)*v-20,color,life:.4+i%3*.15,max:.7})}}
function save(){if(!started||!saveKey)return;try{localStorage.setItem(saveKey,serialize(run));$('#save-status').textContent='Abgeschlossene Hallen auf diesem Gerät gespeichert.'}catch{$('#save-status').textContent='Speichern blockiert — Fortschritt bleibt nur in dieser Sitzung.'}}
async function decode(data){if(!data||typeof data.sheet!=='string'||!data.sheet.startsWith('data:image/png;')||data.sheet.length>20e6)throw Error('Sprite fehlt.');const m=data.metadata;if(!m||![48,64,96].includes(m.frameWidth)||!Number.isFinite(m.anchor?.x)||!Number.isFinite(m.anchor?.y))throw Error('Sprite-Daten ungültig.');const image=new Image();image.src=data.sheet;await image.decode();if(image.width!==m.frameWidth*12||image.height!==m.frameWidth*24)throw Error('Sprite-Größe ungültig.');return {image,meta:m,name:data.name||m.source,usage:m.assetUsage||'character'}}
async function accept(data){if(accepted||data?.type!=='form-pixel-adventure')return;accepted=true;try{assets.hero=await decode(data);saveKey='form-pixel-ruins-v1:'+encodeURIComponent(data.metadata.source||data.name);let saved=null,legacy=null;try{saved=localStorage.getItem(saveKey);legacy=JSON.parse(localStorage.getItem('form-pixel-heimkehr-v1:'+encodeURIComponent(data.metadata.source||data.name))||'null')}catch{}if(saved){run=restore(saved);$('#begin').textContent='Expedition fortsetzen →'}else{run.name=(data.name||'Reisender').slice(0,24);if(legacy?.choice==='garden'||legacy?.choice==='guardian'){run.choice=legacy.choice;run.name=legacy.name||run.name;if(Object.hasOwn(classes,legacy.role))run.role=legacy.role;$('#legacy').disabled=true;$('#legacy-note').textContent='Aus Heimkehr übernommen: Deine damalige Entscheidung öffnet einen eigenen Zugang.'}}
 try{const shelf=JSON.parse(sessionStorage.getItem('form-pixel-props')||'[]');for(const item of shelf.slice(0,3)){try{const asset=await decode(item);assets.props.push(asset);if(asset.usage==='equipment')assets.weapon=asset}catch{}}}catch{}
 if(saved){$('#legacy').disabled=true;$('#legacy-note').textContent='Dein Ursprung und abgeschlossene Hallen bleiben erhalten.'}$('#name').value=run.name;$('#legacy').value=run.choice;$(`input[name=class][value=${run.role}]`).checked=true;$('#class-help').textContent=classHelp[run.role];$('#save-note').textContent=saved?'Du startest am letzten abgeschlossenen Ruhepunkt.':assets.hero.meta.assetUsage==='equipment'?'Ja: Dieses Werkzeug ist jetzt dein spielbarer Held.':'Drei Hallen · ein Geheimnis · dein eigenes Sprite';$('#credits').textContent=data.credit||'Eigenes Modell';$('#begin').disabled=false;hud()}catch(e){accepted=false;$('#save-note').textContent=e.message}}
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==parent)return;if(e.data?.type==='adventure-close'){save();cancelInput();paused=true}else accept(e.data)});
if(parent===window)try{const data=JSON.parse(sessionStorage.getItem('form-pixel-adventure')||'null');if(data)accept(data);else $('#save-note').textContent='Bitte zuerst eine Figur in der Werkstatt wählen.'}catch{}
function cancelInput(){keys.clear();run.charging=false;run.charge=0}
function back(){save();cancelInput();paused=true;if(parent!==window)parent.postMessage({type:'adventure-exit'},location.origin);else location.href='./'}$('#close').onclick=back;
$('#begin').onclick=()=>{if(!assets.hero)return;run.name=$('#name').value.trim()||run.name;run.role=$('input[name=class]:checked').value;run.choice=$('#legacy').value;run.shield=run.choice==='guardian';if(run.phase==='down')retry(run);run.phase='play';started=true;paused=false;$('#intro').hidden=true;$('#pause-panel').hidden=true;say(run.choice==='garden'?'Dein Garten hat einen Wurzelpfad geöffnet. Motte wartet südöstlich. Die erste Halle liegt im Norden.':'Unser Wächter kennt einen alten Zugang hinter dem Spiegelgarten. Zuerst: die Dornenhalle im Norden.');banner('Die lebende Ruine');canvas.focus();save();hud()};
for(const el of document.querySelectorAll('[name=class]'))el.onchange=()=>{run.role=el.value;$('#class-help').textContent=classHelp[run.role];hud()};
function pause(value){if(!$('#intro').hidden||!$('#down').hidden||!$('#ending').hidden||!$('#journal').hidden)return;cancelInput();paused=value;$('#pause-panel').hidden=!value;save();if(!value)canvas.focus();hud()}$('#pause').onclick=()=>pause(!paused);$('#resume').onclick=()=>pause(false);window.addEventListener('blur',()=>pause(true));document.addEventListener('visibilitychange',()=>{if(document.hidden){save();pause(true)}});window.addEventListener('pagehide',save);
const input=()=>({x:Number(keys.has('d')||keys.has('arrowright'))-Number(keys.has('a')||keys.has('arrowleft')),y:Number(keys.has('s')||keys.has('arrowdown'))-Number(keys.has('w')||keys.has('arrowup'))});
function startAttack(){if(blocked())return;beginCharge(run);handle(drain(run));hud()}
function endAttack(){if(blocked()){run.charging=false;return}releaseCharge(run);handle(drain(run));canvas.focus();hud()}
function doDash(){if(blocked())return;dash(run,input());handle(drain(run));canvas.focus();hud()}
$('#attack').onpointerdown=e=>{if(blocked())return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);startAttack()};$('#attack').onpointerup=endAttack;$('#attack').onpointercancel=()=>{run.charging=false;run.charge=0};$('#attack').onclick=e=>{if(e.detail===0){startAttack();endAttack()}};$('#dash').onclick=doDash;
window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA','BUTTON'].includes(e.target.tagName))return;const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','e',' '].includes(k)){e.preventDefault();if(k==='e'){if(!e.repeat)startAttack()}else if(k===' '){if(!e.repeat)doDash()}else if(!blocked())keys.add(k)}if(k==='escape')pause(!paused)});window.addEventListener('keyup',e=>{keys.delete(e.key.toLowerCase());if(e.key.toLowerCase()==='e')endAttack()});
for(const b of document.querySelectorAll('[data-dir]')){const key={up:'w',left:'a',down:'s',right:'d'}[b.dataset.dir];let pressedAt=0;b.onpointerdown=e=>{if(blocked())return;pressedAt=performance.now();e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(key)};b.onpointerup=()=>{keys.delete(key);if(blocked())return;if(performance.now()-pressedAt<230){const[dX,dY]={w:[0,-32],a:[-32,0],s:[0,32],d:[32,0]}[key];run.path=pathTo(run,{x:run.x+dX,y:run.y+dY})}};for(const ev of['pointercancel','lostpointercapture'])b.addEventListener(ev,()=>keys.delete(key));b.onclick=e=>{if(e.detail===0&&!blocked()){const[dX,dY]={w:[0,-32],a:[-32,0],s:[0,32],d:[32,0]}[key];run.path=pathTo(run,{x:run.x+dX,y:run.y+dY})}}}
canvas.onpointerdown=e=>{if(blocked())return;const b=canvas.getBoundingClientRect(),mx=(e.clientX-b.left)*canvas.width/b.width,my=(e.clientY-b.top)*canvas.height/b.height,dest=art.worldPoint(mx,my),route=pathTo(run,dest);if(route.length){run.path=route;burst(dest.x,dest.y,'#dad397',7)}else speak('Wähle Steinboden. Die Siegel öffnen sich nach jeder Halle.');canvas.focus()};
$('#guide').onclick=()=>{if(blocked())return;run.path=pathTo(run,nextTarget(run));speak('Zum goldenen Ziel. Du steuerst Angriffe und Ausweichen selbst.');canvas.focus()};
$('#retry').onclick=()=>{retry(run);$('#down').hidden=true;paused=false;cancelInput();handle(drain(run));canvas.focus();hud()};$('#down-class').onclick=()=>{$('#down').hidden=true;$('#intro').hidden=false;$('#begin').textContent='Mit dieser Klasse erneut versuchen →';$('#name').value=run.name};
function prepareFresh(){try{localStorage.setItem(saveKey+':archive:'+Date.now(),serialize(run))}catch{speak('Archivieren nicht möglich. Dein Fortschritt bleibt erhalten.');return}const{name,role,choice}=run;run=createRun();Object.assign(run,{name,role,choice});started=false;paused=false;fx=[];cancelInput();for(const id of ['#ending','#journal','#down','#pause-panel'])$(id).hidden=true;$('#intro').hidden=false;$('#name').value=name;$('#legacy').disabled=false;$('#legacy').value=choice;$('#legacy-note').textContent='Neue Expedition. Dein bisheriger Lauf bleibt lokal archiviert.';$('#begin').textContent='Neue Expedition beginnen →';hud()}
$('#new-run').onclick=prepareFresh;$('#restart-book').onclick=prepareFresh;$('#explore-home').onclick=()=>{$('#ending').hidden=true;canvas.focus();hud()};
$('#book').onclick=()=>{if(!$('#intro').hidden||!$('#down').hidden||!$('#ending').hidden)return;priorPause=paused;cancelInput();$('#pause-panel').hidden=true;$('#entries').replaceChildren();const lines=[run.choice==='garden'?'Dein Lichtgarten hat einen Wurzelpfad zur verborgenen Gärtnerin geöffnet.':'Der alte Wächter hat einen Zugang südlich des Spiegelgartens offengelegt.',...run.cleared.map(r=>r===1?'Ihr habt die Dornenhalle befriedet. Der erste Ruhepunkt hält euer Licht.':r===2?'Im Spiegelgarten habt ihr gelernt, Raum und Deckung zu nutzen.':'Das verwurzelte Herz ist frei. Die Ruine atmet ruhig.'),...(run.secret?['Motte hat euch einen Lebensfunken geschenkt: acht Herzen.']:[]),...(run.parries?[run.parries+' Mal hast du einen Angriff pariert.']:[]),...(run.returned?['Lumi hat dem Herz zu Hause einen Platz gegeben.']:[])];for(const line of lines){const li=document.createElement('li');li.textContent=line;$('#entries').append(li)}$('#class-instructions').textContent=classHelp[run.role];$('#journal').hidden=false;$('#book-close').focus();hud()};$('#book-close').onclick=()=>{$('#journal').hidden=true;paused=priorPause;$('#pause-panel').hidden=!paused;canvas.focus();hud()};
function handle(events){for(const e of events){if(e.type==='attack'){if(e.role!=='bow')fx.push({...e,life:.27,max:.27});sound(e.role==='sword'?180:e.role==='mage'?390:e.power>.65?750:530,'triangle',.12)}if(e.type==='hitEnemy'){fx.push({type:'number',text:String(e.amount),x:e.x,y:e.y-54,vy:-32,vx:0,life:.6,max:.6});burst(e.x,e.y,'#efd4a2',12);shake=reduced?0:1.8;hitstop=.025;sound(120,'triangle',.07)}if(e.type==='kill'){burst(e.x,e.y,'#bfd9a3',30);sound(490,'sine',.18)}if(e.type==='wall'){speak('Mauerstoß! Zusätzlicher Schaden und Betäubung.');burst(e.x,e.y,'#c8bbf6',24)}if(e.type==='parry'){speak('PERFEKT PARIERT · Dein nächster Schwung ist verstärkt.');banner('✦ Sonnenkonter');burst(run.x,run.y,'#fff0b1',35);sound(880,'sine',.3)}if(e.type==='shield'){speak('Der Segen deines Wächters hat den Treffer abgefangen.');burst(run.x,run.y,'#b5e0d9',25)}if(e.type==='hurt'){burst(run.x,run.y,'#dcad9b',15);shake=reduced?0:4;sound(95,'triangle',.2)}if(e.type==='dash')burst(e.x,e.y,classes[run.role].color,12);if(e.type==='slam')for(const m of e.marks)fx.push({type:'slam',x:m.x,y:m.y,radius:m.r,life:.35,max:.35});
 if(e.type==='enter'){banner(roomNames[e.room]);say(e.room===1?'Die Dornläufer verraten ihren Weg. Warte auf die rote Linie — dann zur Seite.':e.room===2?'Die Blüten zielen dorthin, wo du gerade stehst. Bewegung ist deine Deckung.':e.room===3?'Es greift aus Angst an. Verlasse die Kreise. Wenn es ausatmet, öffnet sich sein Kern.':e.room===4?'Motte! Dein Zuhause hat uns diesen Weg gezeigt. Sprich sie mit deiner Fähigkeit an.':'Hier wartet immer ein Licht auf dich.')}
 if(e.type==='clear'){banner(e.room===3?'Das Herz ist frei.':'Halle befriedet · Ruhepunkt erwacht');say(e.room===3?'Ich höre es wieder. Ganz leise. Lass uns das Herz nach Hause bringen.':e.room===1?'Du hast seinen Rhythmus gefunden. Atme durch. Dein Licht ist wieder voll.':'Der letzte Weg ist offen. Wir sind zusammen bis hierher gekommen.');sound(660,'sine',.4);save()}
 if(e.type==='secret'){banner('Mottes Lebensfunke');say('Motte sagt: Danke, dass du zu Hause Platz für Hoffnung geschaffen hast. Nimm diesen Funken mit.');burst(markers.secret.x,markers.secret.y,'#f0e6b1',55);save()}
 if(e.type==='down'){cancelInput();$('#down').hidden=false;$('#retry').focus();save()}
 if(e.type==='retry')say('Ich habe dein Licht festgehalten. Die offenen Hallen bleiben offen.');
 if(e.type==='win'){cancelInput();$('#ending-copy').textContent=run.choice==='garden'?'Zwischen den Blüten schlägt jetzt ein zweites Herz. Lumi bleibt einen Moment ganz still. „Du hast diesem Ort mehr als Licht gebracht.“':'Der Wächter neigt seinen Kopf vor dem befreiten Herz. Lumi lächelt. „Jetzt beschützen sie diesen Ort gemeinsam.“';$('#ending').hidden=false;$('#explore-home').focus();save();sound(740,'sine',.5)}}}
function hud(){const c=classes[run.role];$('#hero-name').textContent=run.name;$('#hero-detail').textContent=c.name+(assets.weapon?' · '+assets.weapon.name:' · Lumi an deiner Seite');$('#health').textContent='♥'.repeat(Math.max(0,run.hp))+'♡'.repeat(Math.max(0,run.maxHp-run.hp));$('#health').setAttribute('aria-label',run.hp+' von '+run.maxHp+' Herzen');$('#seals').textContent='◆ '.repeat(run.cleared.length)+'◇ '.repeat(3-run.cleared.length);$('#room-name').textContent=roomNames[run.room]||'ZWISCHEN DEN HALLEN';$('#objective').textContent=objective(run);const nearSecret=!run.secret&&Math.hypot(run.x-markers.secret.x,run.y-markers.secret.y)<85;$('#attack strong').textContent=nearSecret?'Motte ansprechen':run.charging?(run.charge>=.7?'✦ Voll geladen!':Math.round(run.charge/.7*100)+' %'):run.cooldown>0?run.cooldown.toFixed(1)+' s':c.skill;$('#attack small').textContent=nearSecret?'E · Lebensfunke':run.role==='bow'?'E halten & lösen':'E · Angriff';$('#attack').classList.toggle('charging',run.charging);$('#attack').disabled=blocked()||run.cooldown>0;$('#dash strong').textContent=run.dashCooldown>0?run.dashCooldown.toFixed(1)+' s':run.role==='sword'?'Parierdash':'Dash';$('#dash').disabled=blocked()||run.dashCooldown>0;$('#guide').disabled=blocked();const boss=run.enemies.find(e=>e.type==='boss');$('#boss-hud').hidden=run.room!==3||boss.hp<=0;$('#boss-health').style.width=100*boss.hp/boss.maxHp+'%';$('#boss-state').textContent=boss.state==='windup'?'RAUS AUS DEN KREISEN':boss.state==='recover'?'KERN OFFEN · JETZT ANGREIFEN':boss.hp<=20?'Das Herz schlägt schneller.':'Wurzeln schützen seinen Kern.';canvas.setAttribute('aria-label',`Lebende Ruine: ${run.name}, ${c.name}. ${run.hp} von ${run.maxHp} Herzen. Hallen ${run.cleared.length}/3. Position ${Math.round(run.x)}, ${Math.round(run.y)}. ${objective(run)} Gegner: ${run.enemies.filter(e=>e.room===run.room&&e.hp>0).map(e=>e.type+' '+e.hp+'/'+e.maxHp+' '+e.state).join(', ')||'keine'}.`)}
function tick(now){const dt=Math.min(.04,(now-last)/1000||.016);last=now;clock+=dt;hitstop=Math.max(0,hitstop-dt);if(!blocked()&&hitstop<=0){handle(step(run,dt,input()));saveTimer+=dt;if(saveTimer>4){save();saveTimer=0}}for(const f of fx){f.life-=dt;f.x+=(f.vx||0)*dt;f.y+=(f.vy||0)*dt}fx=fx.filter(f=>f.life>0);shake=Math.max(0,shake-dt*25);art.draw(run,assets,fx,clock,dt,reduced,shake);if(assets.hero&&!$('#intro').hidden){const c=$('#portrait').getContext('2d'),n=assets.hero.meta.frameWidth;c.clearRect(0,0,256,256);c.imageSmoothingEnabled=false;c.drawImage(assets.hero.image,(reduced?0:Math.floor(clock*12)%12)*n,9*n,n,n,0,0,256,256)}hudTimer+=dt;if(hudTimer>.1){hud();hudTimer=0}requestAnimationFrame(tick)}
window.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const p=['#down','#ending','#journal','#pause-panel'].map($).find(el=>!el.hidden);if(!p)return;const a=[...p.querySelectorAll('button')].filter(el=>!el.disabled);if(e.shiftKey&&(document.activeElement===a[0]||!p.contains(document.activeElement))){e.preventDefault();a.at(-1)?.focus()}else if(!e.shiftKey&&(document.activeElement===a.at(-1)||!p.contains(document.activeElement))){e.preventDefault();a[0]?.focus()}});hud();requestAnimationFrame(tick);

