import assert from 'node:assert/strict';
import {createRun,classes,markers,roomAt,pathTo,walkable,tile,attack,beginCharge,releaseCharge,dash,step,drain,retry,serialize,restore} from './ruins-core.js';
import {suggestUsage} from './asset-usage.js';
const checks=[];
function advance(s,n=1,input={x:0,y:0}){for(let i=0;i<n;i++)step(s,.02,input)}
function go(s,p){s.path=pathTo(s,p);let n=0;while(Math.hypot(s.x-p.x,s.y-p.y)>15&&n++<12000){advance(s);if(s.phase==='down')retry(s);if(!s.path.length)s.path=pathTo(s,p)}assert.ok(n<12000,'route completes');}
for(const choice of ['garden','guardian']){const s=createRun();s.choice=choice;assert.equal(pathTo(s,markers.second).length,0);assert.ok(pathTo(s,markers.secret).length>0=== (choice==='garden'));s.cleared=[1];assert.ok(pathTo(s,markers.second).length>0);assert.equal(pathTo(s,markers.boss).length,0);s.cleared=[1,2];assert.ok(pathTo(s,markers.boss).length>0);assert.ok(pathTo(s,markers.secret).length>0);checks.push(choice+' routes and gates');}
const paused=createRun();const px=paused.x;advance(paused,10,{x:1,y:0});assert.equal(paused.x,px);assert.equal(attack(paused),false);assert.equal(dash(paused),false);
for(const role of Object.keys(classes)){const s=createRun();s.phase='play';s.role=role;s.x=320;s.y=272;const e=s.enemies[0];e.timer=30;assert.ok(attack(s,1));if(role==='bow')advance(s,15);assert.ok(e.hp<e.maxHp,role+' damages target');assert.equal(attack(s),false);checks.push(role+' functional attack and cooldown');}
const charged=createRun();charged.phase='play';charged.role='bow';beginCharge(charged);advance(charged,40);releaseCharge(charged);assert.equal(charged.shots[0].damage,7);assert.equal(charged.shots[0].pierce,2);checks.push('held bow charge produces piercing shot');
const parry=createRun();parry.phase='play';parry.role='sword';parry.x=368;parry.y=272;parry.enemies[0].state='charge';parry.enemies[0].timer=.4;parry.enemies[0].vx=0;parry.enemies[0].vy=0;dash(parry,{x:0,y:1});advance(parry);assert.equal(parry.parries,1);assert.equal(parry.hp,7);assert.ok(parry.empowered>0);checks.push('timed sword dash parries and empowers');
const magic=createRun();magic.phase='play';magic.role='mage';magic.x=220;magic.y=300;const m=magic.enemies[0];m.x=115;m.y=300;m.hp=m.maxHp=20;attack(magic);assert.ok(drain(magic).some(e=>e.type==='wall'));assert.equal(m.hp,13);checks.push('mage wall impact deals bonus damage');
const blocked=createRun();blocked.phase='play';blocked.role='bow';blocked.x=624;blocked.y=300;const enemy=blocked.enemies[2];enemy.x=800;enemy.y=300;blocked.direction=2;attack(blocked,1);advance(blocked,80);assert.equal(enemy.hp,enemy.maxHp);checks.push('closed gate blocks projectile');
const dead=createRun();dead.phase='down';dead.cleared=[1];dead.checkpoint=1;dead.enemies[0].hp=0;retry(dead);assert.equal(dead.hp,7);assert.equal(dead.enemies[0].hp,0);assert.equal(dead.enemies[2].hp,7);checks.push('retry preserves completed rooms');
const secret=createRun();secret.phase='play';Object.assign(secret,markers.secret);attack(secret);assert.ok(secret.secret);assert.equal(secret.maxHp,8);checks.push('optional encounter grants lasting heart');
for(const role of Object.keys(classes))for(const choice of ['garden','guardian']){
 const s=createRun();s.phase='play';s.role=role;s.choice=choice;s.shield=choice==='guardian';
 for(const room of [1,2,3]){go(s,room===1?{x:304,y:432}:room===2?{x:864,y:320}:{x:1504,y:624});let ticks=0;
 while(!s.cleared.includes(room)&&ticks++<25000){if(s.phase==='down'){retry(s);go(s,room===1?{x:304,y:432}:room===2?{x:864,y:320}:{x:1504,y:624})}if(roomAt(s)!==room){s.path=pathTo(s,room===1?{x:304,y:400}:room===2?{x:864,y:320}:{x:1504,y:624});step(s,.02);continue}const e=s.enemies.filter(e=>e.room===room&&e.hp>0).sort((a,b)=>Math.hypot(s.x-a.x,s.y-a.y)-Math.hypot(s.x-b.x,s.y-b.y))[0];if(!e)break;const d=Math.hypot(e.x-s.x,e.y-s.y),range=role==='sword'?65:role==='mage'?115:240;let input={x:0,y:0};const mark=e.type==='boss'&&e.state==='windup'?e.marks.find(p=>Math.hypot(s.x-p.x,s.y-p.y)<p.r+25):null;if(mark){input={x:s.x-mark.x||1,y:s.y-mark.y||.3};dash(s,input)}else if(d>range){input={x:e.x-s.x,y:e.y-s.y}}if(role==='bow'){if(!s.charging&&s.cooldown===0)beginCharge(s);if(s.charge>=.72)releaseCharge(s)}else attack(s);if(e.state==='windup'&&e.timer<.18&&e.type==='charger'&&d<150&&roomAt(s)===room)dash(s,{x:1,y:0});step(s,.02,input);assert.ok(walkable(s,s.x,s.y));}
 if(!s.cleared.includes(room))console.log({role,choice,room,x:s.x,y:s.y,hp:s.hp,phase:s.phase,cooldown:s.cooldown,charging:s.charging,charge:s.charge,defeats:s.defeats,enemies:s.enemies.filter(e=>e.room===room)});assert.ok(s.cleared.includes(room),role+' '+choice+' room '+room+' completed');}
 go(s,markers.home);assert.ok(s.returned);const back=restore(serialize(s));assert.deepEqual(back.cleared,[1,2,3]);assert.equal(back.returned,true);assert.equal(back.role,role);assert.equal(back.choice,choice);checks.push(role+' / '+choice+' full combat, return and save');
}
assert.equal(restore('{bad').phase,'intro');assert.equal(restore(JSON.stringify({version:1,role:'constructor',cleared:[3]})).cleared.length,0);assert.equal(suggestUsage('sword.glb').usage,'equipment');assert.equal(suggestUsage('chair.glb').usage,'object');assert.equal(suggestUsage('unknown.glb').usage,'character');checks.push('save validation and editable asset suggestions');
console.log(JSON.stringify({pass:true,checks},null,2));


